//! Origin authentication for one provisioned peer and one operation attempt.
//!
//! A valid signature authenticates a peer's claim, not its truth. This module
//! cannot issue native publication, completion, retry, release or epoch authority.
//! Key provisioning is external policy. Session freshness relies on OS entropy
//! and is probabilistic, not a durable incarnation or restart-safe deduplication.

use ed25519_dalek::{Signature, VerifyingKey};
use fe2o3_runtime_model::{
    DISTRIBUTED_OPERATION_DESCRIPTION_BYTES_V1, DISTRIBUTED_PUBLICATION_RECEIPT_BYTES_V1,
    DistributedObservationEventV1, DistributedPublicationContractErrorV1,
    ModelDistributedOperationBindingV1, ModelDistributedPublicationRecordV1,
    ModelDistributedReceiptDispositionV1, UntrustedDistributedPublicationReceiptV1,
};

#[cfg(test)]
mod tests;

/// Distinct from the receipt description and external-anchor signing domains.
pub const DISTRIBUTED_RECEIPT_ORIGIN_SIGNING_DOMAIN_V1: &[u8] =
    b"FE2O3/DISTRIBUTED-RECEIPT-ORIGIN/V1\0";
pub const DISTRIBUTED_RECEIPT_ORIGIN_MESSAGE_BYTES_V1: usize =
    DISTRIBUTED_RECEIPT_ORIGIN_SIGNING_DOMAIN_V1.len()
        + 32
        + 32
        + DISTRIBUTED_OPERATION_DESCRIPTION_BYTES_V1
        + DISTRIBUTED_PUBLICATION_RECEIPT_BYTES_V1;

/// An externally provisioned peer key, not proof of membership or key ownership.
///
/// The caller must establish the association between this key and the expected
/// participant out of band. No key discovery, rotation or certificate policy is
/// supplied here. Anchor/issuer keys are not interchangeable types.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct DistributedReceiptPeerKeyV1(VerifyingKey);

impl DistributedReceiptPeerKeyV1 {
    pub fn from_provisioned_bytes(
        bytes: [u8; 32],
    ) -> Result<Self, DistributedReceiptIngressErrorV1> {
        let key = VerifyingKey::from_bytes(&bytes)
            .map_err(|_| DistributedReceiptIngressErrorV1::InvalidPeerKey)?;
        if key.is_weak() {
            return Err(DistributedReceiptIngressErrorV1::InvalidPeerKey);
        }
        Ok(Self(key))
    }

    pub fn to_bytes(self) -> [u8; 32] {
        self.0.to_bytes()
    }
}

/// Public challenge bytes generated by the ingress, with no caller setter.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct DistributedReceiptChallengeV1([u8; 32]);

impl DistributedReceiptChallengeV1 {
    pub const fn to_bytes(self) -> [u8; 32] {
        self.0
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum DistributedReceiptIngressErrorV1 {
    InvalidPeerKey,
    EntropyUnavailable,
    WrongLength,
    InvalidSignature,
    Receipt(DistributedPublicationContractErrorV1),
}

impl core::fmt::Display for DistributedReceiptIngressErrorV1 {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::InvalidPeerKey => f.write_str("invalid distributed receipt peer key"),
            Self::EntropyUnavailable => f.write_str("distributed receipt entropy unavailable"),
            Self::WrongLength => f.write_str("wrong distributed receipt length"),
            Self::InvalidSignature => f.write_str("invalid distributed receipt origin signature"),
            Self::Receipt(error) => write!(f, "distributed receipt rejected: {error:?}"),
        }
    }
}

impl std::error::Error for DistributedReceiptIngressErrorV1 {}

/// An accepted, origin-authenticated peer claim. It is still not native evidence.
///
/// The descriptive receipt returned by `receipt` retains its untrusted model
/// type. No method converts this wrapper to an operational authority.
///
/// ```compile_fail
/// use fe2o3_runtime::OriginAuthenticatedDistributedReceiptV1;
/// let forged = OriginAuthenticatedDistributedReceiptV1 {};
/// ```
///
/// ```compile_fail
/// use fe2o3_runtime::{OriginAuthenticatedDistributedReceiptV1, WorkerV3Gfx942ExecutionAuthorityV1};
/// fn requires_authority<T: WorkerV3Gfx942ExecutionAuthorityV1>(_: T) {}
/// fn convert(claim: OriginAuthenticatedDistributedReceiptV1) {
///     requires_authority(claim);
/// }
/// ```
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct OriginAuthenticatedDistributedReceiptV1 {
    receipt: UntrustedDistributedPublicationReceiptV1,
    peer_key: DistributedReceiptPeerKeyV1,
    challenge: DistributedReceiptChallengeV1,
    disposition: ModelDistributedReceiptDispositionV1,
}

impl OriginAuthenticatedDistributedReceiptV1 {
    pub const fn receipt(self) -> UntrustedDistributedPublicationReceiptV1 {
        self.receipt
    }

    pub const fn peer_key(self) -> DistributedReceiptPeerKeyV1 {
        self.peer_key
    }

    pub const fn challenge(self) -> DistributedReceiptChallengeV1 {
        self.challenge
    }

    pub const fn disposition(self) -> ModelDistributedReceiptDispositionV1 {
        self.disposition
    }
}

/// Fixed-capacity ingress for one key, one challenge and one exact operation.
///
/// `open` obtains fresh OS entropy; it does not establish a connection. The caller
/// must provision the key and every expected coordinate from its own policy.
/// The ingress cannot be cloned; challenge bytes can be read but not selected.
/// There is no reconnect, key replacement, epoch replacement or record reset.
/// Opening another ingress is a separate probabilistically fresh session, not
/// durable deduplication of an attempt or authorization to retry it.
///
/// ```compile_fail
/// use fe2o3_runtime::DistributedReceiptChallengeV1;
/// let selected = DistributedReceiptChallengeV1([1; 32]);
/// ```
///
/// ```compile_fail
/// use fe2o3_runtime::DistributedReceiptIngressV1;
/// fn fork(ingress: &DistributedReceiptIngressV1) -> DistributedReceiptIngressV1 {
///     Clone::clone(ingress)
/// }
/// ```
///
/// ```compile_fail
/// use fe2o3_runtime::DistributedReceiptIngressV1;
/// use fe2o3_runtime_model::{ModelDistributedOperationBindingV1, ModelDistributedPublicationRecordV1};
/// fn reconnect(ingress: &mut DistributedReceiptIngressV1, next_epoch: ModelDistributedOperationBindingV1) {
///     ingress.record = ModelDistributedPublicationRecordV1::new(next_epoch);
/// }
/// ```
#[derive(Debug)]
pub struct DistributedReceiptIngressV1 {
    peer_key: DistributedReceiptPeerKeyV1,
    challenge: DistributedReceiptChallengeV1,
    record: ModelDistributedPublicationRecordV1,
}

impl DistributedReceiptIngressV1 {
    /// Obtain a fresh challenge from Linux/Android `getrandom`, with no fallback.
    /// Unsupported targets and entropy errors fail closed. OS entropy may block
    /// while the kernel random pool initializes; no wall-clock bound is claimed.
    ///
    /// ```no_run
    /// use fe2o3_runtime::{DistributedReceiptIngressErrorV1, DistributedReceiptIngressV1, DistributedReceiptPeerKeyV1};
    /// use fe2o3_runtime_model::ModelDistributedOperationBindingV1;
    /// fn admit(provisioned_key: [u8; 32], expected: ModelDistributedOperationBindingV1)
    ///     -> Result<DistributedReceiptIngressV1, DistributedReceiptIngressErrorV1>
    /// {
    ///     DistributedReceiptIngressV1::open(
    ///         DistributedReceiptPeerKeyV1::from_provisioned_bytes(provisioned_key)?, expected,
    ///     )
    /// }
    /// ```
    pub fn open(
        peer_key: DistributedReceiptPeerKeyV1,
        expected: ModelDistributedOperationBindingV1,
    ) -> Result<Self, DistributedReceiptIngressErrorV1> {
        Ok(Self {
            peer_key,
            challenge: fresh_challenge()?,
            record: ModelDistributedPublicationRecordV1::new(expected),
        })
    }

    pub const fn peer_key(&self) -> DistributedReceiptPeerKeyV1 {
        self.peer_key
    }

    pub const fn challenge(&self) -> DistributedReceiptChallengeV1 {
        self.challenge
    }

    pub const fn expected_binding(&self) -> ModelDistributedOperationBindingV1 {
        self.record.binding()
    }

    /// Exact signature preimage: domain || peer key || challenge || expected
    /// operation description || supplied receipt bytes. All fields have fixed
    /// lengths; no private key, signing operation or transport is exposed.
    /// Constructing this preimage neither decodes nor accepts the supplied bytes.
    pub fn signing_preimage(
        &self,
        receipt: &[u8; DISTRIBUTED_PUBLICATION_RECEIPT_BYTES_V1],
    ) -> [u8; DISTRIBUTED_RECEIPT_ORIGIN_MESSAGE_BYTES_V1] {
        let mut message = [0; DISTRIBUTED_RECEIPT_ORIGIN_MESSAGE_BYTES_V1];
        let expected = self.record.binding().canonical_description();
        let mut remaining = message.as_mut_slice();
        for field in [
            DISTRIBUTED_RECEIPT_ORIGIN_SIGNING_DOMAIN_V1,
            self.peer_key.0.as_bytes().as_slice(),
            self.challenge.0.as_slice(),
            expected.as_slice(),
            receipt.as_slice(),
        ] {
            let (target, suffix) = remaining.split_at_mut(field.len());
            target.copy_from_slice(field);
            remaining = suffix;
        }
        message
    }

    /// Verify origin before decoding and applying the model's sequence rules.
    /// Every failure leaves the record unchanged. Accepted claims have no
    /// authority over a native queue, allocation, epoch or other ingress.
    pub fn accept_signed_receipt(
        &mut self,
        bytes: &[u8],
        signature: &[u8; 64],
    ) -> Result<OriginAuthenticatedDistributedReceiptV1, DistributedReceiptIngressErrorV1> {
        let bytes: &[u8; DISTRIBUTED_PUBLICATION_RECEIPT_BYTES_V1] = bytes
            .try_into()
            .map_err(|_| DistributedReceiptIngressErrorV1::WrongLength)?;
        self.peer_key
            .0
            .verify_strict(
                &self.signing_preimage(bytes),
                &Signature::from_bytes(signature),
            )
            .map_err(|_| DistributedReceiptIngressErrorV1::InvalidSignature)?;
        let receipt = UntrustedDistributedPublicationReceiptV1::decode_untrusted_description(bytes)
            .map_err(DistributedReceiptIngressErrorV1::Receipt)?;
        let disposition = self
            .record
            .record_untrusted_receipt(receipt)
            .map_err(DistributedReceiptIngressErrorV1::Receipt)?;
        Ok(OriginAuthenticatedDistributedReceiptV1 {
            receipt,
            peer_key: self.peer_key,
            challenge: self.challenge,
            disposition,
        })
    }

    /// Last accepted descriptive claim, not a receipt of native completion.
    pub fn last_receipt(&self) -> Option<UntrustedDistributedPublicationReceiptV1> {
        self.record.last_receipt()
    }

    pub const fn connection_interrupted(&self) -> bool {
        self.record.connection_interrupted()
    }

    /// Connection loss is sticky and rejects new claims; exact duplicates still
    /// work. Timeout and observer-drop notifications do not synthesize outcomes.
    pub fn observe(&mut self, event: DistributedObservationEventV1) {
        self.record.observe(event);
    }
}

fn fresh_challenge() -> Result<DistributedReceiptChallengeV1, DistributedReceiptIngressErrorV1> {
    for _ in 0..4 {
        let mut bytes = [0_u8; 32];
        let mut filled = 0;
        while filled < bytes.len() {
            #[cfg(not(test))]
            let count = os_entropy(&mut bytes[filled..])?;
            #[cfg(test)]
            let count = tests::entropy_read(&mut bytes[filled..])?;
            if count == 0 || count > bytes.len() - filled {
                return Err(DistributedReceiptIngressErrorV1::EntropyUnavailable);
            }
            filled += count;
        }
        if bytes != [0; 32] {
            return Ok(DistributedReceiptChallengeV1(bytes));
        }
    }
    Err(DistributedReceiptIngressErrorV1::EntropyUnavailable)
}

#[cfg(any(target_os = "linux", target_os = "android"))]
fn os_entropy(bytes: &mut [u8]) -> Result<usize, DistributedReceiptIngressErrorV1> {
    rustix::rand::getrandom(bytes, rustix::rand::GetRandomFlags::empty())
        .map_err(|_| DistributedReceiptIngressErrorV1::EntropyUnavailable)
}

#[cfg(not(any(target_os = "linux", target_os = "android")))]
fn os_entropy(_bytes: &mut [u8]) -> Result<usize, DistributedReceiptIngressErrorV1> {
    Err(DistributedReceiptIngressErrorV1::EntropyUnavailable)
}
