[package]
name = "fe2o3-device"
version = "0.1.0"
publish = false
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "No-std device-side API for fe2o3 kernels."

[dependencies]
fe2o3-macros.workspace = true

[dev-dependencies]
fe2o3-amd-target.workspace = true
sha2.workspace = true
trybuild = "1"

[lib]
name = "fe2o3_device"
