use super::*;
use fe2o3_kir_debugger::{
    DebugSessionV1, DebugWaveWidthV1, DebuggerLimitsV1, capture_debugger_run_v1,
};
use fe2o3_kir_sim::{
    SimulationDebugCaptureLimitsV1, SimulationDebugRecordKindV1, SimulationLimitsV1,
};

// Positive rows are generated by executing the unchanged retained raw-KIR
// tutorial. These tests make no ordinary-Rust or hardware provenance claim.
fn backend() -> SimulatorBackendV1 {
    let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap();
    let input = crate::load_debug_simulation_input_v1(
        &root.join("crates/fe2o3-kir-sim-cli/tutorial/fill-v1/kernel.kir"),
        &root.join("crates/fe2o3-kir-sim-cli/tutorial/fill-v1/request.json"),
    )
    .unwrap();
    SimulatorBackendV1::new(input, DebugWaveWidthV1::Wave32).unwrap()
}

fn select_last_checkpoint(backend: &mut SimulatorBackendV1) {
    let index = backend
        .session
        .transcript()
        .records()
        .iter()
        .rposition(|record| matches!(record.kind, SimulationDebugRecordKindV1::Checkpoint { .. }))
        .unwrap();
    backend.session.seek_record_index(index);
    backend.revision += 1;
}

fn request(backend: &SimulatorBackendV1, access: bool, scan: u16) -> ResourceRequestV1 {
    let page = ResourceQueryPageV1 {
        max_items: 16,
        max_scanned: scan,
        token: None,
    };
    let expected_snapshot = Box::new(backend.current_anchor(None).unwrap());
    if access {
        ResourceRequestV1::QueryMemoryAccesses {
            schema: ResourceRequestSchemaV1::V1,
            request_id: 1,
            expected_revision: backend.revision,
            expected_snapshot,
            filter: ResourceMemoryAccessFilterV1 {
                scope: ExecutionScopeSelectorV1::Dispatch,
                allocation: None,
                address_space: None,
                access: None,
                range: None,
            },
            page,
        }
    } else {
        ResourceRequestV1::QueryAllocations {
            schema: ResourceRequestSchemaV1::V1,
            request_id: 1,
            expected_revision: backend.revision,
            expected_snapshot,
            address_space: None,
            page,
        }
    }
}

fn continuation(backend: &mut SimulatorBackendV1) -> ResourceRequestV1 {
    let mut request = request(backend, true, 1);
    let response = backend.handle_resource_queries_v1(request.clone());
    response
        .validate_for_request(&request, backend.protocol_limits)
        .unwrap();
    let ResourceResponseV1::Ok {
        page: ResourcePageInfoV1 {
            next_token: Some(token),
            ..
        },
        ..
    } = response
    else {
        panic!("expected continuation");
    };
    if let ResourceRequestV1::QueryMemoryAccesses {
        page, request_id, ..
    } = &mut request
    {
        page.token = Some(token);
        *request_id = 2;
    }
    request
}

fn assert_error(response: ResourceResponseV1, code: DebugErrorCodeV1) {
    response.validate(ProtocolLimitsV1::default()).unwrap();
    assert!(
        matches!(response, ResourceResponseV1::Error { error: DebugErrorV1 { code: actual, state_changed: false, .. }, .. } if actual == code)
    );
}

#[test]
fn actual_inventory_and_access_rows_roundtrip_without_execution_mutation() {
    let mut backend = backend();
    select_last_checkpoint(&mut backend);
    let before = backend.session_view();
    let query = request(&backend, false, 256);
    let response = backend.handle_resource_queries_v1(query.clone());
    response
        .validate_for_request(&query, backend.protocol_limits)
        .unwrap();
    let ResourceResponseV1::Ok {
        result: ResourceQueryResultV1::Allocations { allocations },
        ..
    } = &response
    else {
        panic!("expected inventory");
    };
    assert_eq!(allocations.len(), 1);
    assert_eq!(allocations[0].capacity_bytes.get(), 16);
    assert_eq!(
        allocations[0].allocation,
        AllocationIdentityV1 {
            ordinal: 1,
            generation: 0
        }
    );
    assert_eq!(
        allocations[0].owning_scope,
        ResourceFactUnavailableV1::NotRepresented
    );
    let query = request(&backend, true, 256);
    let response = backend.handle_resource_queries_v1(query.clone());
    response
        .validate_for_request(&query, backend.protocol_limits)
        .unwrap();
    let ResourceResponseV1::Ok {
        result: ResourceQueryResultV1::MemoryAccesses { accesses },
        ..
    } = &response
    else {
        panic!("expected accesses");
    };
    assert_eq!(accesses.len(), 4);
    for (index, row) in accesses.iter().enumerate() {
        assert_eq!(row.range.byte_offset.get(), index as u64 * 4);
        assert_eq!(row.range.byte_len.get(), 4);
        assert_eq!(row.access, ResourceMemoryAccessKindV1::WriteCommitted);
        assert_eq!(
            row.source_association,
            ResourceFactUnavailableV1::NotRepresented
        );
    }
    let mut output = Vec::new();
    write_resource_response_v1(&mut output, &response, backend.protocol_limits).unwrap();
    assert_eq!(
        decode_resource_response_line_v1(&output, backend.protocol_limits).unwrap(),
        response
    );
    assert_eq!(backend.session_view(), before);
}

#[test]
fn bounded_empty_pages_traverse_actual_history_without_duplicates() {
    let mut backend = backend();
    select_last_checkpoint(&mut backend);
    let mut query = request(&backend, true, 1);
    let mut offsets = Vec::new();
    let mut scanned = 0;
    loop {
        let response = backend.handle_resource_queries_v1(query.clone());
        response
            .validate_for_request(&query, backend.protocol_limits)
            .unwrap();
        let ResourceResponseV1::Ok {
            page,
            result: ResourceQueryResultV1::MemoryAccesses { accesses },
            ..
        } = response
        else {
            panic!("expected page");
        };
        assert!(page.scanned <= 1);
        scanned += u64::from(page.scanned);
        offsets.extend(accesses.into_iter().map(|row| row.range.byte_offset.get()));
        match page.next_token {
            None => break,
            Some(token) => {
                if let ResourceRequestV1::QueryMemoryAccesses {
                    page, request_id, ..
                } = &mut query
                {
                    page.token = Some(token);
                    *request_id += 1;
                }
            }
        }
    }
    assert_eq!(offsets, [0, 4, 8, 12]);
    assert_eq!(scanned, backend.cursor_sequence());
    assert!(backend.resource_queries.cursors.is_empty());
}

#[test]
fn consumed_wrong_filter_and_cross_session_tokens_fail_closed() {
    let mut first = backend();
    select_last_checkpoint(&mut first);
    let mut second = backend();
    select_last_checkpoint(&mut second);
    let query = continuation(&mut first);
    assert_error(
        second.handle_resource_queries_v1(query.clone()),
        DebugErrorCodeV1::InvalidCursor,
    );
    let response = first.handle_resource_queries_v1(query.clone());
    response
        .validate_for_request(&query, first.protocol_limits)
        .unwrap();
    assert_error(
        first.handle_resource_queries_v1(query),
        DebugErrorCodeV1::InvalidCursor,
    );
    let mut changed = continuation(&mut first);
    if let ResourceRequestV1::QueryMemoryAccesses { filter, .. } = &mut changed {
        filter.address_space = Some(AddressSpaceV1::Workgroup);
    }
    assert_error(
        first.handle_resource_queries_v1(changed),
        DebugErrorCodeV1::InvalidCursor,
    );
}

#[test]
fn entire_anchor_and_reverse_same_cursor_revision_are_required() {
    let mut backend = backend();
    select_last_checkpoint(&mut backend);
    for variant in 0..4 {
        let mut query = request(&backend, true, 1);
        if let ResourceRequestV1::QueryMemoryAccesses {
            expected_snapshot, ..
        } = &mut query
        {
            match variant {
                0 => expected_snapshot.site = None,
                1 => {
                    expected_snapshot.cursor.configuration_identity =
                        OpaqueIdentityV1::new([8; 32]).unwrap()
                }
                2 => {
                    expected_snapshot.frame = Some(1);
                    expected_snapshot.occurrence = Some(1);
                }
                _ => {
                    if let ExecutionScopeV1::Lane {
                        logical_workitem, ..
                    } = &mut expected_snapshot.scope
                    {
                        logical_workitem[0] += 1;
                    }
                }
            }
        }
        assert_error(
            backend.handle_resource_queries_v1(query),
            DebugErrorCodeV1::InvalidCursor,
        );
    }
    let old = continuation(&mut backend);
    let index = backend.session.cursor_record_index().unwrap();
    backend.session.seek_entry();
    backend.revision += 1;
    backend.session.seek_record_index(index);
    backend.revision += 1;
    assert_error(
        backend.handle_resource_queries_v1(old.clone()),
        DebugErrorCodeV1::StaleRevision,
    );
    assert!(backend.resource_queries.cursors.is_empty());
    let mut changed = old;
    if let ResourceRequestV1::QueryMemoryAccesses {
        expected_snapshot,
        expected_revision,
        ..
    } = &mut changed
    {
        **expected_snapshot = backend.current_anchor(None).unwrap();
        *expected_revision = backend.revision;
    }
    assert_error(
        backend.handle_resource_queries_v1(changed),
        DebugErrorCodeV1::InvalidCursor,
    );
}

#[test]
fn cursor_store_is_bounded_and_never_evicts_into_unchecked_authority() {
    let mut backend = backend();
    select_last_checkpoint(&mut backend);
    for _ in 0..MAX_RESOURCE_CURSOR_ENTRIES_V1 {
        let _ = continuation(&mut backend);
    }
    assert_eq!(backend.resource_queries.cursors.len(), 256);
    let query = request(&backend, true, 1);
    assert_error(
        backend.handle_resource_queries_v1(query),
        DebugErrorCodeV1::ResourceLimit,
    );
    assert_eq!(backend.resource_queries.cursors.len(), 256);
}

#[test]
fn missing_capture_and_partial_history_keep_actual_producer_limits() {
    for (memory_budget, record_budget) in [(1, 4096), (4096, 3)] {
        let mut backend = backend();
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .unwrap()
            .parent()
            .unwrap();
        let input = crate::load_debug_simulation_input_v1(
            &root.join("crates/fe2o3-kir-sim-cli/tutorial/fill-v1/kernel.kir"),
            &root.join("crates/fe2o3-kir-sim-cli/tutorial/fill-v1/request.json"),
        )
        .unwrap();
        let run = capture_debugger_run_v1(
            &backend.module,
            &input.request,
            input.simulation_target(),
            SimulationLimitsV1::default(),
            SimulationDebugCaptureLimitsV1::new(16, 256, 16, memory_budget).unwrap(),
            DebuggerLimitsV1::new(record_budget, 32768, 1 << 20).unwrap(),
            DebugWaveWidthV1::Wave32,
        );
        backend.session = DebugSessionV1::new(run.transcript).into();
        select_last_checkpoint(&mut backend);
        let query = request(&backend, record_budget == 3, 256);
        let response = backend.handle_resource_queries_v1(query.clone());
        response
            .validate_for_request(&query, backend.protocol_limits)
            .unwrap();
        if memory_budget == 1 {
            assert!(
                matches!(response, ResourceResponseV1::Unavailable { reason: ResourceQueryUnavailableReasonV1::MemoryByteLimit, required: Some(required), .. } if required.get() == 32)
            );
        } else {
            assert!(matches!(
                response,
                ResourceResponseV1::Ok {
                    page: ResourcePageInfoV1 {
                        completeness: CaptureCompletenessV1::Truncated {
                            emitted_events: 3,
                            dropped_events: None,
                            ..
                        },
                        ..
                    },
                    ..
                }
            ));
        }
    }
}

#[test]
fn noncheckpoint_and_terminated_sessions_do_not_fabricate_current_resources() {
    let mut backend = backend();
    select_last_checkpoint(&mut backend);
    let query = request(&backend, false, 256);
    let index = backend
        .session
        .transcript()
        .records()
        .iter()
        .position(|record| matches!(record.kind, SimulationDebugRecordKindV1::Memory { .. }))
        .unwrap();
    backend.session.seek_record_index(index);
    assert_error(
        backend.handle_resource_queries_v1(query.clone()),
        DebugErrorCodeV1::InvalidState,
    );
    select_last_checkpoint(&mut backend);
    let query = request(&backend, false, 256);
    backend.terminated = true;
    assert_error(
        backend.handle_resource_queries_v1(query),
        DebugErrorCodeV1::InvalidState,
    );
}

#[test]
fn direct_malformed_request_returns_encodable_read_only_error() {
    let mut backend = backend();
    select_last_checkpoint(&mut backend);
    let mut query = request(&backend, false, 256);
    if let ResourceRequestV1::QueryAllocations { request_id, .. } = &mut query {
        *request_id = 0;
    }
    let before = backend.session_view();
    let response = backend.handle_resource_queries_v1(query);
    assert!(matches!(
        response,
        ResourceResponseV1::Error {
            request_id: None,
            ..
        }
    ));
    encode_resource_response_line_v1(&response, backend.protocol_limits).unwrap();
    assert_eq!(backend.session_view(), before);
}
