[package]
name = "cargo-fe2o3"
version = "0.1.0"
default-run = "cargo-fe2o3"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Cargo subcommand for fe2o3."

[dependencies]
cap-primitives = "=4.0.2"
fe2o3-rustc-invocation.workspace = true
rustix.workspace = true
serde_json = "1"
sha2 = { version = "0.11.0", default-features = false }

[[bin]]
name = "cargo-fe2o3"
path = "src/main.rs"

[[bin]]
name = "fe2o3-rustc-wrapper"
path = "src/bin/fe2o3-rustc-wrapper.rs"
