[package]
name = "fe2o3-macros"
version = "0.1.0"
publish = false
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Procedural macros for fe2o3 kernels."

[lib]
proc-macro = true

[dependencies]
fe2o3-artifacts.workspace = true
proc-macro2 = { workspace = true, features = ["span-locations"] }
proc-macro-crate.workspace = true
quote.workspace = true
reserved-fe2o3-symbols.workspace = true
syn = { workspace = true, features = ["visit", "visit-mut"] }
