[package]
name = "fe2o3-production-explicit-bin-fixture"
version = "0.1.0"
edition = "2024"
publish = false
autobins = false

[workspace]

[features]
explicit_bin_export = []

[dependencies]
fe2o3-device = { path = "../../../../fe2o3-device" }

[target.'cfg(not(target_arch = "amdgpu"))'.dependencies]
fe2o3-host = { path = "../../../../fe2o3-host" }

[lib]
name = "fe2o3_production_explicit_bin_fixture"
path = "src/lib.rs"

[[bin]]
name = "fe2o3-production-explicit-bin-fixture"
path = "src/explicit_bin_export.rs"
required-features = ["explicit_bin_export"]
test = false
bench = false

[profile.dev]
panic = "abort"
