// @generated by scripts/generate-formal-compiler-v3-spec.py; do not edit.
use vstd::prelude::*;

verus! {

pub open spec fn formal_compiler_v3_schema_version() -> nat { 1 }
pub open spec fn formal_compiler_v3_claim_version() -> nat { 3 }
pub open spec fn formal_compiler_v3_word_bits() -> nat { 32 }
pub open spec fn formal_compiler_v3_byte_width() -> nat { 4 }
pub open spec fn formal_compiler_v3_helper_parameters() -> nat { 2 }
pub open spec fn formal_compiler_v3_branch_arms() -> nat { 2 }
pub open spec fn formal_compiler_v3_maximum_call_depth() -> nat { 2 }
pub open spec fn formal_compiler_v3_minimum_loop_trip_count() -> nat { 1 }
pub open spec fn formal_compiler_v3_maximum_loop_trip_count() -> nat { 4 }
pub open spec fn formal_compiler_v3_readonly_accesses() -> nat { 2 }
pub open spec fn formal_compiler_v3_disjoint_writes() -> nat { 1 }

}
