// @generated by scripts/generate-formal-compiler-v3-spec.py; do not edit.

/// Declarative V3 manifest schema version.
pub const FORMAL_COMPILER_V3_SCHEMA_VERSION: u16 = 1;
/// Formal Compiler claim generation.
pub const FORMAL_COMPILER_V3_CLAIM_VERSION: u16 = 3;
/// Stable name of the exact composed V3 fragment.
pub const FORMAL_COMPILER_V3_CLAIM_NAME: &str = "guarded-u32-xor-helper-store-v1";
/// Closed scalar word width.
pub const FORMAL_COMPILER_V3_WORD_BITS: u16 = 32;
/// Closed typed access width in bytes.
pub const FORMAL_COMPILER_V3_BYTE_WIDTH: u8 = 4;
/// Exact helper parameter count.
pub const FORMAL_COMPILER_V3_HELPER_PARAMETERS: u8 = 2;
/// Exact helper branch-arm count.
pub const FORMAL_COMPILER_V3_BRANCH_ARMS: u8 = 2;
/// Maximum depth modeled by the bounded call-stack theorem.
pub const FORMAL_COMPILER_V3_MAXIMUM_CALL_DEPTH: u8 = 2;
/// Minimum trip count modeled by the bounded loop theorem.
pub const FORMAL_COMPILER_V3_MINIMUM_LOOP_TRIP_COUNT: u8 = 1;
/// Maximum trip count modeled by the bounded loop theorem.
pub const FORMAL_COMPILER_V3_MAXIMUM_LOOP_TRIP_COUNT: u8 = 4;
/// Exact readonly access count in the composed kernel fragment.
pub const FORMAL_COMPILER_V3_READONLY_ACCESSES: u8 = 2;
/// Exact disjoint write count in the composed kernel fragment.
pub const FORMAL_COMPILER_V3_DISJOINT_WRITES: u8 = 1;
/// The formal byte codec is little endian.
pub const FORMAL_COMPILER_V3_USES_LITTLE_ENDIAN: bool = true;
/// The composed access theorem binds a runtime extent value.
pub const FORMAL_COMPILER_V3_USES_DYNAMIC_EXTENT: bool = true;
/// Closed scalar operation vocabulary shared with the generated formal model.
pub const FORMAL_COMPILER_V3_SCALAR_OPERATIONS: &[&str] = &[
    "bitxor",
    "checked-add",
    "truncate",
    "unsigned-equal",
    "unsigned-less-than",
    "wrapping-add",
    "zero-extend",
];
