// @generated by scripts/generate-formal-compiler-v3-spec.py; do not edit.

/// Declarative V3 manifest schema version.
pub const FORMAL_COMPILER_V3_SCHEMA_VERSION: u16 = 1;
/// Formal Compiler claim generation.
pub const FORMAL_COMPILER_V3_CLAIM_VERSION: u16 = 3;
/// Stable name of the exact composed V3 fragment.
pub const FORMAL_COMPILER_V3_CLAIM_NAME: &str = "guarded-u32-xor-helper-store-v1";
/// Closed scalar word width.
pub const FORMAL_COMPILER_V3_WORD_BITS: u16 = 32;
/// Closed typed access width in bytes.
pub const FORMAL_COMPILER_V3_BYTE_WIDTH: u8 = 4;
/// Exact helper parameter count.
pub const FORMAL_COMPILER_V3_HELPER_PARAMETERS: u8 = 2;
/// Exact helper branch-arm count.
pub const FORMAL_COMPILER_V3_BRANCH_ARMS: u8 = 2;
/// The helper branches on whether the XOR result equals zero.
pub const FORMAL_COMPILER_V3_HELPER_BRANCHES_ON_XOR_ZERO: bool = true;
/// The helper's nonzero arm returns an arbitrary `u32` fallback.
pub const FORMAL_COMPILER_V3_NONZERO_RETURNS_FALLBACK_U32: bool = true;
/// Exact stack-frame count in the production-connected root/helper claim.
pub const FORMAL_COMPILER_V3_PRODUCTION_STACK_FRAMES: u8 = 2;
/// Exact loop count in the production-connected claim.
pub const FORMAL_COMPILER_V3_PRODUCTION_LOOP_TRIP_COUNT: u8 = 0;
/// Maximum stack-frame count in the non-authoritative structured model.
pub const FORMAL_COMPILER_V3_MODELED_MAXIMUM_STACK_FRAMES: u8 = 2;
/// Minimum trip count in the non-authoritative loop model.
pub const FORMAL_COMPILER_V3_MODELED_MINIMUM_LOOP_TRIP_COUNT: u8 = 1;
/// Maximum trip count in the non-authoritative loop model.
pub const FORMAL_COMPILER_V3_MODELED_MAXIMUM_LOOP_TRIP_COUNT: u8 = 4;
/// Exact readonly access count in the composed kernel fragment.
pub const FORMAL_COMPILER_V3_READONLY_ACCESSES: u8 = 2;
/// Exact disjoint write count in the composed kernel fragment.
pub const FORMAL_COMPILER_V3_DISJOINT_WRITES: u8 = 1;
/// Exact allocation count covered by the conjunction guard.
pub const FORMAL_COMPILER_V3_GUARDED_ALLOCATIONS: u8 = 3;
/// Exact ordered runtime-extent count; extents are not assumed equal.
pub const FORMAL_COMPILER_V3_DYNAMIC_EXTENTS: u8 = 3;
/// Exact predicate count in the ordered short-circuit guard chain.
pub const FORMAL_COMPILER_V3_GUARD_PREDICATES: u8 = 3;
/// The production guard is an ordered short-circuit chain.
pub const FORMAL_COMPILER_V3_USES_ORDERED_SHORT_CIRCUIT_GUARD: bool = true;
/// Every modeled access must be in bounds for the guarded path to execute.
pub const FORMAL_COMPILER_V3_GUARDS_ALL_ACCESSES: bool = true;
/// Every access byte offset is `gid * byte_width`.
pub const FORMAL_COMPILER_V3_USES_GID_TIMES_BYTE_WIDTH: bool = true;
/// The three modeled allocations must be pairwise disjoint.
pub const FORMAL_COMPILER_V3_REQUIRES_PAIRWISE_DISJOINT_ALLOCATIONS: bool = true;
/// The formal byte codec is little endian.
pub const FORMAL_COMPILER_V3_USES_LITTLE_ENDIAN: bool = true;
/// The composed access theorem binds a runtime extent value.
pub const FORMAL_COMPILER_V3_USES_DYNAMIC_EXTENT: bool = true;
/// Production-connected scalar operation vocabulary.
pub const FORMAL_COMPILER_V3_PRODUCTION_SCALAR_OPERATIONS: &[(&str, u8)] = &[
    ("bitxor", 1),
    ("unsigned-equal", 2),
    ("unsigned-less-than", 3),
];
/// Additional scalar operations proved only in the non-authoritative model.
pub const FORMAL_COMPILER_V3_MODELED_ONLY_SCALAR_OPERATIONS: &[(&str, u8)] = &[
    ("checked-add", 4),
    ("truncate", 5),
    ("wrapping-add", 6),
    ("zero-extend", 7),
];
