//! Branded, target-neutral execution capabilities.
//!
//! The source types in this module make kernel, workgroup, subgroup, and
//! synchronization-epoch substitution visible to Rust's type checker. They do
//! not prove convergence, race freedom, target support, or launch validity.
//! Production lowering must establish those dynamic obligations before it may
//! replace any fail-closed terminal in this module.

use core::marker::PhantomData;

use crate::capability_memory::{
    AtomicReadWrite, CapabilityMemoryView, GlobalAddressSpace, ReadOnly, WorkgroupAddressSpace,
};
use crate::{
    Global, KernelCapabilityBrand, KernelContext, KernelLaunch, KernelTarget, LdsElement,
    MatrixCapability, SubgroupLane, SubgroupWidth, SubgroupWidth32, SubgroupWidth64,
    WorkgroupCollectiveElement,
};

type Invariant<T> = fn(T) -> T;
type InvariantLifetime<'scope> = fn(&'scope mut ()) -> &'scope mut ();

/// Version of the branded source execution-capability contract.
pub const EXECUTION_CAPABILITY_CONTRACT_VERSION_V1: u16 = 1;

mod sealed {
    pub trait Epoch {}
    pub trait ReusableEpoch<'phase> {}
    pub trait Scope {}
    pub trait Ordering {}
    pub trait Spaces {}
    pub trait WorkgroupBarrier {}
    pub trait SubgroupBarrier {}
    pub trait WorkgroupFence {}
    pub trait SubgroupFence {}
    pub trait CollectiveWidth {}
    pub trait MatrixWidth {}
    pub trait AtomicElement {}
    pub trait AtomicLoadOrder {}
    pub trait AtomicStoreOrder {}
    pub trait AtomicRmwOrder {}
    pub trait AtomicFailureOrder {}
    pub trait AtomicOrderPair {}
    pub trait WorkgroupAtomicScope {}
}

/// Initial synchronization epoch for one compiler-issued workgroup scope.
#[derive(Debug)]
pub enum InitialEpoch {}

/// Epoch reached after one typed barrier, collective, or async wait.
pub struct NextEpoch<Previous> {
    _previous: PhantomData<Invariant<Previous>>,
}

/// Fresh synchronization epoch issued for one dynamic workgroup phase.
///
/// The lifetime is generated by [`ReusableWorkgroup::with_phase`]. It cannot be
/// named by the caller before the phase begins or retained after it ends.
#[rustc_diagnostic_item = "fe2o3_device_dynamic_phase_epoch_v1"]
pub struct DynamicPhaseEpoch<'phase> {
    _phase: PhantomData<InvariantLifetime<'phase>>,
}

/// Sealed synchronization-epoch identity.
pub trait SynchronizationEpoch: sealed::Epoch {}

/// Sealed proof that an epoch belongs to one reusable dynamic phase.
pub trait ReusableSynchronizationEpoch<'phase>:
    SynchronizationEpoch + sealed::ReusableEpoch<'phase>
{
}

impl sealed::Epoch for InitialEpoch {}
impl SynchronizationEpoch for InitialEpoch {}
impl<Previous: SynchronizationEpoch> sealed::Epoch for NextEpoch<Previous> {}
impl<Previous: SynchronizationEpoch> SynchronizationEpoch for NextEpoch<Previous> {}
impl sealed::Epoch for DynamicPhaseEpoch<'_> {}
impl SynchronizationEpoch for DynamicPhaseEpoch<'_> {}
impl<'phase> sealed::ReusableEpoch<'phase> for DynamicPhaseEpoch<'phase> {}
impl<'phase> ReusableSynchronizationEpoch<'phase> for DynamicPhaseEpoch<'phase> {}
impl<'phase, Previous> sealed::ReusableEpoch<'phase> for NextEpoch<Previous> where
    Previous: ReusableSynchronizationEpoch<'phase>
{
}
impl<'phase, Previous> ReusableSynchronizationEpoch<'phase> for NextEpoch<Previous> where
    Previous: ReusableSynchronizationEpoch<'phase>
{
}

/// Invariant identity for one generative workgroup scope.
pub struct WorkgroupBrand<'workgroup, KernelBrand> {
    _workgroup: PhantomData<InvariantLifetime<'workgroup>>,
    _kernel: PhantomData<Invariant<KernelBrand>>,
}

/// Invariant identity retained when one workgroup enters reusable phases.
#[rustc_diagnostic_item = "fe2o3_device_reusable_workgroup_brand_v1"]
pub struct ReusableWorkgroupBrand<'workgroup, KernelBrand> {
    _workgroup: PhantomData<InvariantLifetime<'workgroup>>,
    _kernel: PhantomData<Invariant<KernelBrand>>,
}

/// Invariant identity for one subgroup in one workgroup epoch.
pub struct SubgroupBrand<'workgroup, Width, KernelBrand, Epoch> {
    _workgroup: PhantomData<Invariant<WorkgroupBrand<'workgroup, KernelBrand>>>,
    _width: PhantomData<Invariant<Width>>,
    _epoch: PhantomData<Invariant<Epoch>>,
}

/// System memory scope.
#[derive(Debug)]
pub enum SystemScope {}
/// Device memory scope.
#[derive(Debug)]
pub enum DeviceScope {}
/// Workgroup memory and execution scope.
#[derive(Debug)]
pub enum WorkgroupScope {}
/// Subgroup memory and execution scope.
#[derive(Debug)]
pub enum SubgroupScope {}

/// Relaxed memory ordering.
#[derive(Debug)]
pub enum Relaxed {}
/// Acquire memory ordering.
#[derive(Debug)]
pub enum Acquire {}
/// Release memory ordering.
#[derive(Debug)]
pub enum Release {}
/// Acquire-release memory ordering.
#[derive(Debug)]
pub enum AcquireRelease {}
/// Sequentially consistent memory ordering.
#[derive(Debug)]
pub enum SequentiallyConsistent {}

/// Global memory only.
#[derive(Debug)]
pub enum GlobalMemory {}
/// Workgroup-shared memory only.
#[derive(Debug)]
pub enum WorkgroupMemory {}
/// Global and workgroup-shared memory.
#[derive(Debug)]
pub enum GlobalAndWorkgroupMemory {}

/// Sealed execution or memory scope identity.
pub trait MemoryScope: sealed::Scope {}
/// Sealed memory-order identity.
pub trait MemoryOrdering: sealed::Ordering {}
/// Sealed address-space set identity.
pub trait MemorySpaces: sealed::Spaces {}

macro_rules! sealed_markers {
    ($private:ident => $public:ident: $($ty:ty),+ $(,)?) => {
        $(
            impl sealed::$private for $ty {}
            impl $public for $ty {}
        )+
    };
}

sealed_markers!(Scope => MemoryScope: SystemScope, DeviceScope, WorkgroupScope, SubgroupScope);
sealed_markers!(Ordering => MemoryOrdering: Relaxed, Acquire, Release, AcquireRelease, SequentiallyConsistent);
sealed_markers!(Spaces => MemorySpaces: GlobalMemory, WorkgroupMemory, GlobalAndWorkgroupMemory);

/// Type-level barrier or fence tuple.
pub struct MemorySemantics<Scope, Ordering, Spaces> {
    _scope: PhantomData<Invariant<Scope>>,
    _ordering: PhantomData<Invariant<Ordering>>,
    _spaces: PhantomData<Invariant<Spaces>>,
}

/// Sealed proof that a tuple is a supported workgroup barrier contract.
pub trait WorkgroupBarrierSemantics: sealed::WorkgroupBarrier {}
/// Sealed proof that a tuple is a supported subgroup barrier contract.
pub trait SubgroupBarrierSemantics: sealed::SubgroupBarrier {}
/// Sealed proof that a tuple is a supported workgroup fence contract.
pub trait WorkgroupFenceSemantics: sealed::WorkgroupFence {}
/// Sealed proof that a tuple is a supported subgroup fence contract.
pub trait SubgroupFenceSemantics: sealed::SubgroupFence {}

macro_rules! workgroup_barrier_semantics {
    ($($spaces:ty),+ $(,)?) => {
        $(
            impl sealed::WorkgroupBarrier
                for MemorySemantics<WorkgroupScope, AcquireRelease, $spaces>
            {}
            impl WorkgroupBarrierSemantics
                for MemorySemantics<WorkgroupScope, AcquireRelease, $spaces>
            {}
        )+
    };
}

macro_rules! subgroup_barrier_semantics {
    ($($spaces:ty),+ $(,)?) => {
        $(
            impl sealed::SubgroupBarrier
                for MemorySemantics<SubgroupScope, AcquireRelease, $spaces>
            {}
            impl SubgroupBarrierSemantics
                for MemorySemantics<SubgroupScope, AcquireRelease, $spaces>
            {}
        )+
    };
}

workgroup_barrier_semantics!(GlobalMemory, WorkgroupMemory, GlobalAndWorkgroupMemory);
subgroup_barrier_semantics!(GlobalMemory, WorkgroupMemory, GlobalAndWorkgroupMemory);

macro_rules! fence_semantics {
    ($private:ident, $public:ident, $scope:ty; $($spaces:ty),+ $(,)?) => {
        $(
            impl sealed::$private for MemorySemantics<$scope, Acquire, $spaces> {}
            impl $public for MemorySemantics<$scope, Acquire, $spaces> {}
            impl sealed::$private for MemorySemantics<$scope, Release, $spaces> {}
            impl $public for MemorySemantics<$scope, Release, $spaces> {}
            impl sealed::$private for MemorySemantics<$scope, AcquireRelease, $spaces> {}
            impl $public for MemorySemantics<$scope, AcquireRelease, $spaces> {}
            impl sealed::$private
                for MemorySemantics<$scope, SequentiallyConsistent, $spaces>
            {}
            impl $public for MemorySemantics<$scope, SequentiallyConsistent, $spaces> {}
        )+
    };
}

fence_semantics!(WorkgroupFence, WorkgroupFenceSemantics, WorkgroupScope;
    GlobalMemory, WorkgroupMemory, GlobalAndWorkgroupMemory);
fence_semantics!(SubgroupFence, SubgroupFenceSemantics, SubgroupScope;
    GlobalMemory, WorkgroupMemory, GlobalAndWorkgroupMemory);

/// Linear synchronization token owned by one workgroup capability.
#[must_use = "the synchronization epoch must remain paired with its workgroup"]
pub struct WorkgroupEpoch<'workgroup, KernelBrand, Epoch: SynchronizationEpoch> {
    _workgroup: PhantomData<Invariant<WorkgroupBrand<'workgroup, KernelBrand>>>,
    _epoch: PhantomData<Invariant<Epoch>>,
    _not_send_sync: PhantomData<*mut ()>,
}

/// Compiler-issued authority for the current invocation's current workgroup.
///
/// `with_workgroup` creates the generative `'workgroup` lifetime. This value is
/// move-only and local to the invocation. The epoch type changes only through
/// methods whose compiler terminals represent synchronization.
#[must_use = "workgroup authority carries the current synchronization epoch"]
#[rustc_diagnostic_item = "fe2o3_device_workgroup_capability_v1"]
pub struct WorkgroupCapability<'workgroup, KernelBrand, Epoch: SynchronizationEpoch = InitialEpoch>
{
    size: u64,
    rank: u64,
    epoch: WorkgroupEpoch<'workgroup, KernelBrand, Epoch>,
    _not_send_sync: PhantomData<*mut ()>,
}

/// Workgroup authority that can issue fresh lifetime-branded dynamic phases.
///
/// The outer workgroup and kernel identities never change. Each call to
/// [`Self::with_phase`] exclusively borrows this value and introduces a fresh
/// epoch lifetime, so phase-bound capabilities cannot survive into the next
/// runtime loop iteration.
#[must_use = "reusable workgroup authority owns all dynamic synchronization phases"]
#[rustc_diagnostic_item = "fe2o3_device_reusable_workgroup_v1"]
pub struct ReusableWorkgroup<'workgroup, KernelBrand> {
    size: u64,
    rank: u64,
    _workgroup: PhantomData<Invariant<WorkgroupBrand<'workgroup, KernelBrand>>>,
    _not_send_sync: PhantomData<*mut ()>,
}

/// One persistent workgroup allocation reborrowed under each dynamic phase.
///
/// The allocation identity remains bound to the outer workgroup. A phase can
/// obtain at most one mutable epoch-bound handle from this value, and that
/// handle cannot remain live while a later phase is issued.
#[must_use = "reusable LDS storage must remain owned by its workgroup"]
#[rustc_diagnostic_item = "fe2o3_device_reusable_workgroup_lds_v1"]
pub struct ReusableWorkgroupLds<'workgroup, T: LdsElement, const ELEMENTS: usize, KernelBrand> {
    _storage: PhantomData<&'workgroup mut [T; ELEMENTS]>,
    _workgroup: PhantomData<Invariant<WorkgroupBrand<'workgroup, KernelBrand>>>,
    _not_send_sync: PhantomData<*mut ()>,
}

/// Linear proof that one reusable phase ended at a workgroup barrier.
#[must_use = "a reusable workgroup phase must be completed by its owner"]
#[rustc_diagnostic_item = "fe2o3_device_reusable_phase_completion_v1"]
pub struct ReusablePhaseCompletion<'phase, 'workgroup, KernelBrand> {
    _phase: PhantomData<InvariantLifetime<'phase>>,
    _workgroup: PhantomData<Invariant<WorkgroupBrand<'workgroup, KernelBrand>>>,
    _not_send_sync: PhantomData<*mut ()>,
}

/// Result of publishing an LDS region into the next workgroup epoch.
pub type PublishedLdsTransition<'workgroup, T, const ELEMENTS: usize, KernelBrand, Epoch> = (
    WorkgroupCapability<'workgroup, KernelBrand, NextEpoch<Epoch>>,
    WorkgroupLds<'workgroup, T, ELEMENTS, WorkgroupLdsPublished, KernelBrand, NextEpoch<Epoch>>,
);

/// Result of publishing two disjoint LDS allocations at one exact barrier.
pub type PublishedLdsPairTransition<
    'workgroup,
    A,
    const A_ELEMENTS: usize,
    B,
    const B_ELEMENTS: usize,
    KernelBrand,
    Epoch,
> = (
    WorkgroupCapability<'workgroup, KernelBrand, NextEpoch<Epoch>>,
    WorkgroupLds<'workgroup, A, A_ELEMENTS, WorkgroupLdsPublished, KernelBrand, NextEpoch<Epoch>>,
    WorkgroupLds<'workgroup, B, B_ELEMENTS, WorkgroupLdsPublished, KernelBrand, NextEpoch<Epoch>>,
);

/// Result of a workgroup collective that returns reusable scratch.
pub type WorkgroupCollectiveTransition<'workgroup, T, const ELEMENTS: usize, KernelBrand, Epoch> = (
    WorkgroupCapability<'workgroup, KernelBrand, NextEpoch<Epoch>>,
    WorkgroupLds<'workgroup, T, ELEMENTS, WorkgroupLdsUninitialized, KernelBrand, NextEpoch<Epoch>>,
    T,
);

/// Result of advancing one exact-width subgroup barrier epoch.
pub type SubgroupBarrierTransition<'workgroup, Width, KernelBrand, Epoch> = (
    WorkgroupCapability<'workgroup, KernelBrand, NextEpoch<Epoch>>,
    Subgroup<'workgroup, Width, KernelBrand, NextEpoch<Epoch>>,
);

impl<'workgroup, KernelBrand, Epoch: SynchronizationEpoch>
    WorkgroupCapability<'workgroup, KernelBrand, Epoch>
{
    /// Number of invocations in the current workgroup.
    pub const fn size(&self) -> u64 {
        self.size
    }

    /// Linear rank of this invocation in the current workgroup.
    pub const fn invocation_rank(&self) -> u64 {
        self.rank
    }

    /// Borrows the exact synchronization epoch required by scoped operations.
    pub const fn epoch(&self) -> &WorkgroupEpoch<'workgroup, KernelBrand, Epoch> {
        &self.epoch
    }

    /// Derives an exact-width subgroup capability for this workgroup epoch.
    ///
    /// Target legalization must reject a width unavailable for the selected
    /// target. The returned type does not assert convergence.
    #[rustc_diagnostic_item = "fe2o3_device_subgroup_current_v1"]
    pub fn subgroup<Width: SubgroupWidth>(
        &self,
    ) -> Subgroup<'workgroup, Width, KernelBrand, Epoch> {
        Subgroup::current()
    }

    /// Allocates one compiler-owned workgroup-memory region.
    ///
    /// The compiler must prove a disjoint allocation and exact extent. The
    /// source type starts uninitialized; unsupported lowering traps.
    #[inline(never)]
    #[rustc_diagnostic_item = "fe2o3_device_workgroup_lds_allocate_v1"]
    pub fn allocate_lds<T: LdsElement, const ELEMENTS: usize>(
        &self,
    ) -> WorkgroupLds<'workgroup, T, ELEMENTS, WorkgroupLdsUninitialized, KernelBrand, Epoch> {
        const {
            assert!(ELEMENTS > 0, "workgroup memory cannot be empty");
        }
        unreachable!("workgroup LDS allocation requires authenticated lowering")
    }

    /// Executes a barrier with an exact static contract and advances the epoch.
    ///
    /// This type transition prevents stale-epoch capability use. It does not
    /// prove that every participant reaches the barrier; compiler convergence
    /// analysis remains mandatory.
    #[inline(never)]
    #[rustc_diagnostic_item = "fe2o3_device_typed_workgroup_barrier_v1"]
    pub fn barrier<Scope, Ordering, Spaces>(
        self,
    ) -> WorkgroupCapability<'workgroup, KernelBrand, NextEpoch<Epoch>>
    where
        Scope: MemoryScope,
        Ordering: MemoryOrdering,
        Spaces: MemorySpaces,
        MemorySemantics<Scope, Ordering, Spaces>: WorkgroupBarrierSemantics,
    {
        unreachable!("typed workgroup barriers require authenticated lowering")
    }

    /// Executes a barrier for one exact-width subgroup and advances its epoch.
    ///
    /// Advancing the enclosing workgroup token is deliberately conservative:
    /// it prevents any old-epoch workgroup resource from being treated as if
    /// the subgroup barrier had published it to all workgroup invocations.
    #[inline(never)]
    #[rustc_diagnostic_item = "fe2o3_device_typed_subgroup_barrier_v1"]
    pub fn subgroup_barrier<Width, Scope, Ordering, Spaces>(
        self,
        _subgroup: Subgroup<'workgroup, Width, KernelBrand, Epoch>,
    ) -> SubgroupBarrierTransition<'workgroup, Width, KernelBrand, Epoch>
    where
        Width: SubgroupWidth,
        Scope: MemoryScope,
        Ordering: MemoryOrdering,
        Spaces: MemorySpaces,
        MemorySemantics<Scope, Ordering, Spaces>: SubgroupBarrierSemantics,
    {
        unreachable!("typed subgroup barriers require authenticated lowering")
    }

    /// Executes a workgroup-scoped memory fence without asserting convergence.
    #[inline(never)]
    #[rustc_diagnostic_item = "fe2o3_device_typed_workgroup_fence_v1"]
    pub fn fence<Scope, Ordering, Spaces>(&self)
    where
        Scope: MemoryScope,
        Ordering: MemoryOrdering,
        Spaces: MemorySpaces,
        MemorySemantics<Scope, Ordering, Spaces>: WorkgroupFenceSemantics,
    {
        unreachable!("typed workgroup fences require authenticated lowering")
    }

    /// Publishes per-invocation initialization through a workgroup barrier.
    #[inline(never)]
    #[rustc_diagnostic_item = "fe2o3_device_workgroup_lds_publish_v1"]
    pub fn publish_lds<T: LdsElement, const ELEMENTS: usize>(
        self,
        _lds: WorkgroupLds<
            'workgroup,
            T,
            ELEMENTS,
            WorkgroupLdsInvocationInitialized,
            KernelBrand,
            Epoch,
        >,
    ) -> PublishedLdsTransition<'workgroup, T, ELEMENTS, KernelBrand, Epoch> {
        unreachable!("publishing workgroup LDS requires authenticated lowering")
    }

    /// Publishes two initialized LDS allocations through one typed barrier.
    ///
    /// GEMM and attention commonly stage paired operands. Both handles must
    /// belong to this exact old epoch, and both outputs carry the same next
    /// epoch. The implementation reuses the sole authenticated workgroup
    /// barrier terminal rather than introducing a second synchronization path.
    pub fn publish_lds_pair<
        A: LdsElement,
        const A_ELEMENTS: usize,
        B: LdsElement,
        const B_ELEMENTS: usize,
    >(
        self,
        first: WorkgroupLds<
            'workgroup,
            A,
            A_ELEMENTS,
            WorkgroupLdsInvocationInitialized,
            KernelBrand,
            Epoch,
        >,
        second: WorkgroupLds<
            'workgroup,
            B,
            B_ELEMENTS,
            WorkgroupLdsInvocationInitialized,
            KernelBrand,
            Epoch,
        >,
    ) -> PublishedLdsPairTransition<'workgroup, A, A_ELEMENTS, B, B_ELEMENTS, KernelBrand, Epoch>
    {
        let _ = (first, second);
        let workgroup = self.barrier::<WorkgroupScope, AcquireRelease, WorkgroupMemory>();
        let first = WorkgroupLds {
            _storage: PhantomData,
            _state: PhantomData,
            _workgroup: PhantomData,
            _epoch: PhantomData,
            _not_send_sync: PhantomData,
        };
        let second = WorkgroupLds {
            _storage: PhantomData,
            _state: PhantomData,
            _workgroup: PhantomData,
            _epoch: PhantomData,
            _not_send_sync: PhantomData,
        };
        (workgroup, first, second)
    }

    /// Starts one global-to-workgroup asynchronous copy.
    ///
    /// The source must have the read-only global role. The destination is
    /// consumed, so it cannot be read or reused while the copy is pending.
    #[inline(never)]
    #[rustc_diagnostic_item = "fe2o3_device_workgroup_async_copy_v1"]
    pub fn async_copy_from_global<T: LdsElement, const ELEMENTS: usize>(
        &self,
        _source: &Global<'_, T, ReadOnly, KernelBrand>,
        _source_offset: usize,
        _destination: WorkgroupLds<
            'workgroup,
            T,
            ELEMENTS,
            WorkgroupLdsUninitialized,
            KernelBrand,
            Epoch,
        >,
    ) -> PendingAsyncCopy<'workgroup, T, ELEMENTS, KernelBrand, Epoch> {
        unreachable!("async workgroup copies require authenticated lowering")
    }

    /// Waits for one async copy, publishes it, and advances the epoch.
    #[inline(never)]
    #[rustc_diagnostic_item = "fe2o3_device_workgroup_async_wait_v1"]
    pub fn wait_for<T: LdsElement, const ELEMENTS: usize>(
        self,
        _copy: PendingAsyncCopy<'workgroup, T, ELEMENTS, KernelBrand, Epoch>,
    ) -> PublishedLdsTransition<'workgroup, T, ELEMENTS, KernelBrand, Epoch> {
        unreachable!("async workgroup waits require authenticated lowering")
    }

    /// Executes a workgroup sum and advances the synchronization epoch.
    #[inline(never)]
    #[rustc_diagnostic_item = "fe2o3_device_typed_workgroup_reduce_sum_v1"]
    pub fn reduce_sum<T: WorkgroupCollectiveElement, const ELEMENTS: usize>(
        self,
        _scratch: WorkgroupLds<
            'workgroup,
            T,
            ELEMENTS,
            WorkgroupLdsUninitialized,
            KernelBrand,
            Epoch,
        >,
        _value: T,
    ) -> WorkgroupCollectiveTransition<'workgroup, T, ELEMENTS, KernelBrand, Epoch> {
        unreachable!("typed workgroup reduction requires authenticated lowering")
    }

    /// Executes an inclusive workgroup prefix sum and advances the epoch.
    #[inline(never)]
    #[rustc_diagnostic_item = "fe2o3_device_typed_workgroup_inclusive_scan_sum_v1"]
    pub fn inclusive_scan_sum<T: WorkgroupCollectiveElement, const ELEMENTS: usize>(
        self,
        _scratch: WorkgroupLds<
            'workgroup,
            T,
            ELEMENTS,
            WorkgroupLdsUninitialized,
            KernelBrand,
            Epoch,
        >,
        _value: T,
    ) -> WorkgroupCollectiveTransition<'workgroup, T, ELEMENTS, KernelBrand, Epoch> {
        unreachable!("typed workgroup scan requires authenticated lowering")
    }

    /// Executes an exclusive workgroup prefix sum and advances the epoch.
    #[inline(never)]
    #[rustc_diagnostic_item = "fe2o3_device_typed_workgroup_exclusive_scan_sum_v1"]
    pub fn exclusive_scan_sum<T: WorkgroupCollectiveElement, const ELEMENTS: usize>(
        self,
        _scratch: WorkgroupLds<
            'workgroup,
            T,
            ELEMENTS,
            WorkgroupLdsUninitialized,
            KernelBrand,
            Epoch,
        >,
        _value: T,
    ) -> WorkgroupCollectiveTransition<'workgroup, T, ELEMENTS, KernelBrand, Epoch> {
        unreachable!("typed workgroup scan requires authenticated lowering")
    }

    /// Acquires one atomic global location at this workgroup epoch.
    #[rustc_diagnostic_item = "fe2o3_device_scoped_global_atomic_v1"]
    pub fn global_atomic<'memory, T: AtomicElement, Scope>(
        &self,
        view: &'memory CapabilityMemoryView<
            '_,
            T,
            GlobalAddressSpace,
            AtomicReadWrite<Scope>,
            KernelBrand,
        >,
        index: usize,
    ) -> Option<
        ScopedAtomic<
            'memory,
            T,
            GlobalAddressSpace,
            Scope,
            WorkgroupBrand<'workgroup, KernelBrand>,
            Epoch,
        >,
    >
    where
        Scope: WorkgroupAtomicScope,
    {
        (index < view.len()).then_some(ScopedAtomic {
            _memory: PhantomData,
            _element: PhantomData,
            _space: PhantomData,
            _scope: PhantomData,
            _brand: PhantomData,
            _epoch: PhantomData,
            _not_send_sync: PhantomData,
        })
    }

    /// Performs one scoped atomic load.
    #[inline(never)]
    #[rustc_diagnostic_item = "fe2o3_device_scoped_atomic_load_v1"]
    pub fn atomic_load<T, Space, Scope, Ordering>(
        &self,
        _location: &ScopedAtomic<
            '_,
            T,
            Space,
            Scope,
            WorkgroupBrand<'workgroup, KernelBrand>,
            Epoch,
        >,
    ) -> T
    where
        T: AtomicElement,
        Scope: MemoryScope + WorkgroupAtomicScope,
        Ordering: AtomicLoadOrdering,
    {
        unreachable!("scoped atomic loads require authenticated lowering")
    }

    /// Performs one scoped atomic store.
    #[inline(never)]
    #[rustc_diagnostic_item = "fe2o3_device_scoped_atomic_store_v1"]
    pub fn atomic_store<T, Space, Scope, Ordering>(
        &self,
        _location: &ScopedAtomic<
            '_,
            T,
            Space,
            Scope,
            WorkgroupBrand<'workgroup, KernelBrand>,
            Epoch,
        >,
        _value: T,
    ) where
        T: AtomicElement,
        Scope: MemoryScope + WorkgroupAtomicScope,
        Ordering: AtomicStoreOrdering,
    {
        unreachable!("scoped atomic stores require authenticated lowering")
    }

    /// Performs one scoped atomic addition and returns the previous value.
    #[inline(never)]
    #[rustc_diagnostic_item = "fe2o3_device_scoped_atomic_fetch_add_v1"]
    pub fn atomic_fetch_add<T, Space, Scope, Ordering>(
        &self,
        _location: &ScopedAtomic<
            '_,
            T,
            Space,
            Scope,
            WorkgroupBrand<'workgroup, KernelBrand>,
            Epoch,
        >,
        _value: T,
    ) -> T
    where
        T: AtomicElement,
        Scope: MemoryScope + WorkgroupAtomicScope,
        Ordering: AtomicRmwOrdering,
    {
        unreachable!("scoped atomic additions require authenticated lowering")
    }

    /// Performs one scoped atomic compare-exchange.
    #[inline(never)]
    #[rustc_diagnostic_item = "fe2o3_device_scoped_atomic_compare_exchange_v1"]
    pub fn atomic_compare_exchange<T, Space, Scope, Success, Failure>(
        &self,
        _location: &ScopedAtomic<
            '_,
            T,
            Space,
            Scope,
            WorkgroupBrand<'workgroup, KernelBrand>,
            Epoch,
        >,
        _current: T,
        _new: T,
    ) -> Result<T, T>
    where
        T: AtomicElement,
        Scope: MemoryScope + WorkgroupAtomicScope,
        Success: AtomicRmwOrdering,
        Failure: AtomicFailureOrdering,
        AtomicOrderPair<Success, Failure>: ValidAtomicOrderPair,
    {
        unreachable!("scoped atomic compare-exchange requires authenticated lowering")
    }
}

impl<'workgroup, KernelBrand, Epoch> WorkgroupCapability<'workgroup, KernelBrand, Epoch>
where
    Epoch: SynchronizationEpoch,
{
    /// Converts the current linear workgroup token into a reusable phase owner.
    ///
    /// Existing epoch-bound resources are not converted and cannot be used with
    /// a subsequently issued dynamic phase. The outer workgroup identity and
    /// invocation observations are preserved exactly.
    pub fn into_reusable(self) -> ReusableWorkgroup<'workgroup, KernelBrand> {
        ReusableWorkgroup {
            size: self.size,
            rank: self.rank,
            _workgroup: PhantomData,
            _not_send_sync: PhantomData,
        }
    }
}

impl<'workgroup, T, const ELEMENTS: usize, KernelBrand, Epoch>
    WorkgroupLds<'workgroup, T, ELEMENTS, WorkgroupLdsUninitialized, KernelBrand, Epoch>
where
    T: LdsElement,
    Epoch: SynchronizationEpoch,
{
    /// Retains this uninitialized allocation for repeated dynamic phases.
    ///
    /// Initialized or published handles intentionally have no such conversion:
    /// each phase must re-establish initialization and publication under its
    /// own fresh epoch.
    pub fn into_reusable(self) -> ReusableWorkgroupLds<'workgroup, T, ELEMENTS, KernelBrand> {
        ReusableWorkgroupLds {
            _storage: PhantomData,
            _workgroup: PhantomData,
            _not_send_sync: PhantomData,
        }
    }
}

impl<'workgroup, KernelBrand> ReusableWorkgroup<'workgroup, KernelBrand> {
    fn issue_phase<'phase>(
        &'phase mut self,
    ) -> WorkgroupCapability<
        'phase,
        ReusableWorkgroupBrand<'workgroup, KernelBrand>,
        DynamicPhaseEpoch<'phase>,
    > {
        WorkgroupCapability {
            size: self.size,
            rank: self.rank,
            epoch: WorkgroupEpoch {
                _workgroup: PhantomData,
                _epoch: PhantomData,
                _not_send_sync: PhantomData,
            },
            _not_send_sync: PhantomData,
        }
    }

    /// Runs one runtime-selected phase under a fresh synchronization brand.
    ///
    /// The exclusive borrow chooses a fresh lifetime on every call. If `Result`
    /// retains an epoch-bound capability, that borrow remains live and Rust
    /// rejects any attempt to issue the next phase until the stale value is
    /// dropped. The closure must return the unforgeable completion produced by
    /// [`WorkgroupCapability::finish_reusable_phase`].
    pub fn with_phase<'phase, Result>(
        &'phase mut self,
        operation: impl FnOnce(
            WorkgroupCapability<
                'phase,
                ReusableWorkgroupBrand<'workgroup, KernelBrand>,
                DynamicPhaseEpoch<'phase>,
            >,
        ) -> (
            ReusablePhaseCompletion<'phase, 'workgroup, KernelBrand>,
            Result,
        ),
    ) -> Result {
        let (completion, result) = operation(self.issue_phase());
        drop(completion);
        result
    }
}

impl<'phase, 'workgroup, KernelBrand>
    WorkgroupCapability<
        'phase,
        ReusableWorkgroupBrand<'workgroup, KernelBrand>,
        DynamicPhaseEpoch<'phase>,
    >
{
    /// Reborrows one persistent allocation under this phase's fresh epoch.
    ///
    /// The `&'phase mut` borrow prevents a second phase or a second handle for
    /// the same allocation until the current higher-ranked closure ends.
    pub fn bind_reusable_lds<T: LdsElement, const ELEMENTS: usize>(
        &self,
        _storage: &'phase mut ReusableWorkgroupLds<'workgroup, T, ELEMENTS, KernelBrand>,
    ) -> WorkgroupLds<
        'phase,
        T,
        ELEMENTS,
        WorkgroupLdsUninitialized,
        ReusableWorkgroupBrand<'workgroup, KernelBrand>,
        DynamicPhaseEpoch<'phase>,
    > {
        WorkgroupLds {
            _storage: PhantomData,
            _state: PhantomData,
            _workgroup: PhantomData,
            _epoch: PhantomData,
            _not_send_sync: PhantomData,
        }
    }
}

impl<'phase, 'workgroup, KernelBrand, Epoch>
    WorkgroupCapability<'phase, ReusableWorkgroupBrand<'workgroup, KernelBrand>, Epoch>
where
    Epoch: ReusableSynchronizationEpoch<'phase>,
{
    /// Ends this dynamic phase at an acquire-release workgroup-memory barrier.
    ///
    /// The existing typed barrier terminal remains the sole synchronization
    /// operation. This method only seals its advanced token into a completion
    /// that the higher-ranked owner consumes before issuing another phase.
    pub fn finish_reusable_phase(self) -> ReusablePhaseCompletion<'phase, 'workgroup, KernelBrand> {
        let _next = self.barrier::<WorkgroupScope, AcquireRelease, WorkgroupMemory>();
        ReusablePhaseCompletion {
            _phase: PhantomData,
            _workgroup: PhantomData,
            _not_send_sync: PhantomData,
        }
    }
}

/// Target-neutral exact-width subgroup capability.
#[must_use = "subgroup authority remains bound to its workgroup epoch"]
#[rustc_diagnostic_item = "fe2o3_device_subgroup_capability_v1"]
pub struct Subgroup<'workgroup, Width: SubgroupWidth, KernelBrand, Epoch: SynchronizationEpoch> {
    lane: SubgroupLane<Width, SubgroupBrand<'workgroup, Width, KernelBrand, Epoch>>,
    _workgroup: PhantomData<Invariant<WorkgroupBrand<'workgroup, KernelBrand>>>,
    _not_send_sync: PhantomData<*mut ()>,
}

impl<'workgroup, Width, KernelBrand, Epoch> Subgroup<'workgroup, Width, KernelBrand, Epoch>
where
    Width: SubgroupWidth,
    Epoch: SynchronizationEpoch,
{
    fn current() -> Self {
        Self {
            lane: SubgroupLane::current_branded(),
            _workgroup: PhantomData,
            _not_send_sync: PhantomData,
        }
    }

    /// Exact subgroup width required by this capability.
    pub const fn size(&self) -> u32 {
        Width::LANES
    }

    /// Current invocation's lane rank in this subgroup.
    pub const fn lane_rank(&self) -> u32 {
        self.lane.get()
    }

    /// Borrows the branded lane witness used by existing reviewed operations.
    pub const fn lane(
        &self,
    ) -> &SubgroupLane<Width, SubgroupBrand<'workgroup, Width, KernelBrand, Epoch>> {
        &self.lane
    }

    /// Executes a subgroup-scoped memory fence without asserting convergence.
    #[inline(never)]
    #[rustc_diagnostic_item = "fe2o3_device_typed_subgroup_fence_v1"]
    pub fn fence<Scope, Ordering, Spaces>(
        &self,
        _epoch: &WorkgroupEpoch<'workgroup, KernelBrand, Epoch>,
    ) where
        Scope: MemoryScope,
        Ordering: MemoryOrdering,
        Spaces: MemorySpaces,
        MemorySemantics<Scope, Ordering, Spaces>: SubgroupFenceSemantics,
    {
        unreachable!("typed subgroup fences require authenticated lowering")
    }

    /// Returns a subgroup sum under the exact width and epoch contract.
    #[inline(never)]
    #[rustc_diagnostic_item = "fe2o3_device_subgroup_reduce_sum_v1"]
    pub fn reduce_sum<T: WorkgroupCollectiveElement>(
        &self,
        _epoch: &WorkgroupEpoch<'workgroup, KernelBrand, Epoch>,
        _value: T,
    ) -> T
    where
        Width: CollectiveSubgroupWidth,
    {
        unreachable!("subgroup reduction requires authenticated lowering")
    }

    /// Returns an inclusive subgroup prefix sum in increasing lane order.
    #[inline(never)]
    #[rustc_diagnostic_item = "fe2o3_device_subgroup_inclusive_scan_sum_v1"]
    pub fn inclusive_scan_sum<T: WorkgroupCollectiveElement>(
        &self,
        _epoch: &WorkgroupEpoch<'workgroup, KernelBrand, Epoch>,
        _value: T,
    ) -> T
    where
        Width: CollectiveSubgroupWidth,
    {
        unreachable!("subgroup scan requires authenticated lowering")
    }

    /// Issues matrix authority for this exact subgroup and workgroup epoch.
    #[doc(hidden)]
    #[inline(never)]
    #[rustc_diagnostic_item = "fe2o3_device_subgroup_matrix_access_v1"]
    pub fn __compiler_matrix_access(
        &self,
        _epoch: &WorkgroupEpoch<'workgroup, KernelBrand, Epoch>,
    ) -> MatrixCapability<SubgroupBrand<'workgroup, Width, KernelBrand, Epoch>>
    where
        Width: MatrixSubgroupWidth,
    {
        unreachable!("subgroup matrix access requires authenticated lowering")
    }

    /// Runs an existing reviewed matrix operation under this subgroup epoch.
    ///
    /// The borrow of `epoch` lasts for the operation, preventing the enclosing
    /// workgroup capability from advancing while lane-bound fragments are live.
    pub fn with_matrix<'operation, Result>(
        &'operation self,
        epoch: &'operation WorkgroupEpoch<'workgroup, KernelBrand, Epoch>,
        operation: impl FnOnce(
            &MatrixCapability<SubgroupBrand<'workgroup, Width, KernelBrand, Epoch>>,
            &'operation SubgroupLane<Width, SubgroupBrand<'workgroup, Width, KernelBrand, Epoch>>,
        ) -> Result,
    ) -> Result
    where
        Width: MatrixSubgroupWidth,
    {
        let matrix = self.__compiler_matrix_access(epoch);
        operation(&matrix, &self.lane)
    }
}

/// Sealed exact widths admitted by target-neutral subgroup collectives.
pub trait CollectiveSubgroupWidth: SubgroupWidth + sealed::CollectiveWidth {}
/// Sealed exact widths admitted by the currently reviewed matrix terminals.
pub trait MatrixSubgroupWidth: SubgroupWidth + sealed::MatrixWidth {}

sealed_markers!(CollectiveWidth => CollectiveSubgroupWidth: SubgroupWidth32, SubgroupWidth64);
sealed_markers!(MatrixWidth => MatrixSubgroupWidth: SubgroupWidth64);

/// Workgroup-memory state before compiler-proven initialization.
#[derive(Debug)]
pub enum WorkgroupLdsUninitialized {}
/// Workgroup-memory state after one exact write per invocation.
#[derive(Debug)]
pub enum WorkgroupLdsInvocationInitialized {}
/// Workgroup-memory state published into a later synchronization epoch.
#[derive(Debug)]
pub enum WorkgroupLdsPublished {}

/// Workgroup memory bound to one workgroup brand and synchronization epoch.
#[must_use = "workgroup memory must remain paired with its branded epoch"]
#[rustc_diagnostic_item = "fe2o3_device_epoch_workgroup_lds_v1"]
pub struct WorkgroupLds<
    'workgroup,
    T: LdsElement,
    const ELEMENTS: usize,
    State,
    KernelBrand,
    Epoch: SynchronizationEpoch,
> {
    _storage: PhantomData<&'workgroup mut [T; ELEMENTS]>,
    _state: PhantomData<Invariant<State>>,
    _workgroup: PhantomData<Invariant<WorkgroupBrand<'workgroup, KernelBrand>>>,
    _epoch: PhantomData<Invariant<Epoch>>,
    _not_send_sync: PhantomData<*mut ()>,
}

impl<'workgroup, T, const ELEMENTS: usize, KernelBrand, Epoch>
    WorkgroupLds<'workgroup, T, ELEMENTS, WorkgroupLdsUninitialized, KernelBrand, Epoch>
where
    T: LdsElement,
    Epoch: SynchronizationEpoch,
{
    /// Writes `value` to this invocation's linear workgroup slot.
    ///
    /// Production import must prove `ELEMENTS == workgroup.size()` and exactly
    /// one in-bounds write by every participating invocation. The resulting
    /// state records that obligation; it is not a global race proof by itself.
    #[inline(never)]
    #[rustc_diagnostic_item = "fe2o3_device_workgroup_lds_initialize_by_invocation_v1"]
    pub fn initialize_by_invocation(
        self,
        _workgroup: &WorkgroupCapability<'workgroup, KernelBrand, Epoch>,
        _value: T,
    ) -> WorkgroupLds<'workgroup, T, ELEMENTS, WorkgroupLdsInvocationInitialized, KernelBrand, Epoch>
    {
        unreachable!("workgroup LDS initialization requires authenticated lowering")
    }
}

impl<'workgroup, T, const ELEMENTS: usize, KernelBrand, Epoch>
    WorkgroupLds<'workgroup, T, ELEMENTS, WorkgroupLdsPublished, KernelBrand, Epoch>
where
    T: LdsElement + Copy,
    Epoch: SynchronizationEpoch,
{
    /// Reads one published workgroup-memory element in the matching epoch.
    #[inline(never)]
    #[rustc_diagnostic_item = "fe2o3_device_workgroup_lds_read_published_v1"]
    pub fn read(
        &self,
        _workgroup: &WorkgroupCapability<'workgroup, KernelBrand, Epoch>,
        _index: usize,
    ) -> Option<T> {
        unreachable!("published workgroup LDS reads require authenticated lowering")
    }
}

/// Linear pending state for one global-to-workgroup asynchronous copy.
#[must_use = "an async copy must be consumed by its matching wait"]
#[rustc_diagnostic_item = "fe2o3_device_pending_async_copy_v1"]
pub struct PendingAsyncCopy<
    'workgroup,
    T: LdsElement,
    const ELEMENTS: usize,
    KernelBrand,
    Epoch: SynchronizationEpoch,
> {
    _destination: PhantomData<&'workgroup mut [T; ELEMENTS]>,
    _workgroup: PhantomData<Invariant<WorkgroupBrand<'workgroup, KernelBrand>>>,
    _epoch: PhantomData<Invariant<Epoch>>,
    _not_send_sync: PhantomData<*mut ()>,
}

/// Opaque atomic location bound to an address space, scope, brand, and epoch.
#[must_use = "scoped atomic locations remain bound to their issuing epoch"]
pub struct ScopedAtomic<'memory, T, Space, Scope, KernelBrand, Epoch: SynchronizationEpoch> {
    _memory: PhantomData<&'memory mut T>,
    _element: PhantomData<Invariant<T>>,
    _space: PhantomData<Invariant<Space>>,
    _scope: PhantomData<Invariant<Scope>>,
    _brand: PhantomData<Invariant<KernelBrand>>,
    _epoch: PhantomData<Invariant<Epoch>>,
    _not_send_sync: PhantomData<*mut ()>,
}

/// Integer element accepted by scoped atomic terminals.
pub trait AtomicElement: sealed::AtomicElement + Copy {}
/// Ordering accepted by atomic loads.
pub trait AtomicLoadOrdering: MemoryOrdering + sealed::AtomicLoadOrder {}
/// Ordering accepted by atomic stores.
pub trait AtomicStoreOrdering: MemoryOrdering + sealed::AtomicStoreOrder {}
/// Ordering accepted by read-modify-write atomics.
pub trait AtomicRmwOrdering: MemoryOrdering + sealed::AtomicRmwOrder {}
/// Ordering accepted for compare-exchange failure.
pub trait AtomicFailureOrdering: MemoryOrdering + sealed::AtomicFailureOrder {}
/// Scope accepted by atomics issued from a workgroup capability.
pub trait WorkgroupAtomicScope: MemoryScope + sealed::WorkgroupAtomicScope {}

sealed_markers!(AtomicElement => AtomicElement: u32, i32, u64, i64);
sealed_markers!(AtomicLoadOrder => AtomicLoadOrdering: Relaxed, Acquire, SequentiallyConsistent);
sealed_markers!(AtomicStoreOrder => AtomicStoreOrdering: Relaxed, Release, SequentiallyConsistent);
sealed_markers!(AtomicRmwOrder => AtomicRmwOrdering: Relaxed, Acquire, Release, AcquireRelease, SequentiallyConsistent);
sealed_markers!(AtomicFailureOrder => AtomicFailureOrdering: Relaxed, Acquire, SequentiallyConsistent);
sealed_markers!(WorkgroupAtomicScope => WorkgroupAtomicScope: SystemScope, DeviceScope, WorkgroupScope);

/// Type-level compare-exchange success/failure ordering pair.
pub struct AtomicOrderPair<Success, Failure> {
    _success: PhantomData<Invariant<Success>>,
    _failure: PhantomData<Invariant<Failure>>,
}

/// Sealed proof that a compare-exchange ordering pair is valid.
pub trait ValidAtomicOrderPair: sealed::AtomicOrderPair {}

macro_rules! atomic_order_pairs {
    ($($success:ty => [$($failure:ty),+]),+ $(,)?) => {
        $($(
            impl sealed::AtomicOrderPair for AtomicOrderPair<$success, $failure> {}
            impl ValidAtomicOrderPair for AtomicOrderPair<$success, $failure> {}
        )+)+
    };
}

atomic_order_pairs!(
    Relaxed => [Relaxed],
    Acquire => [Relaxed, Acquire],
    Release => [Relaxed],
    AcquireRelease => [Relaxed, Acquire],
    SequentiallyConsistent => [Relaxed, Acquire, SequentiallyConsistent],
);

impl<'kernel, Kernel, Target, Launch> KernelContext<'kernel, Kernel, Target, Launch>
where
    Target: KernelTarget,
    Launch: KernelLaunch,
{
    /// Issues initial-epoch workgroup authority from this exact kernel context.
    #[doc(hidden)]
    #[inline(never)]
    #[rustc_diagnostic_item = "fe2o3_device_workgroup_capability_current_v1"]
    pub fn __compiler_workgroup_capability_current<'workgroup>(
        &'workgroup mut self,
    ) -> WorkgroupCapability<
        'workgroup,
        KernelCapabilityBrand<'kernel, Kernel, Target, Launch>,
        InitialEpoch,
    > {
        unreachable!("workgroup capability issuance requires authenticated lowering")
    }

    /// Opens one generative capability scope for the current workgroup.
    ///
    /// The higher-ranked lifetime prevents workgroup, subgroup, LDS, epoch,
    /// atomic, and async-copy capabilities from escaping into another dynamic
    /// workgroup invocation.
    pub fn with_workgroup<Result>(
        &mut self,
        operation: impl for<'workgroup> FnOnce(
            WorkgroupCapability<
                'workgroup,
                KernelCapabilityBrand<'kernel, Kernel, Target, Launch>,
                InitialEpoch,
            >,
        ) -> Result,
    ) -> Result {
        let workgroup = self.__compiler_workgroup_capability_current();
        operation(workgroup)
    }
}

const _: () = {
    assert!(core::mem::size_of::<WorkgroupEpoch<'static, (), InitialEpoch>>() == 0);
    assert!(
        core::mem::size_of::<
            ScopedAtomic<'static, u32, GlobalAddressSpace, SystemScope, (), InitialEpoch>,
        >() == 0
    );
    assert!(
        core::mem::size_of::<
            WorkgroupLds<'static, u32, 64, WorkgroupLdsUninitialized, (), InitialEpoch>,
        >() == 0
    );
};

// Keep both address-space identities in the reviewed source closure. Scoped
// workgroup atomics are intentionally not exposed until their LDS provenance
// and initialization transition have a production importer.
const _: fn() = || {
    let _ = core::mem::size_of::<
        ScopedAtomic<'static, u32, WorkgroupAddressSpace, WorkgroupScope, (), InitialEpoch>,
    >();
};

#[cfg(test)]
mod tests {
    use core::marker::PhantomData;

    use super::{
        InitialEpoch, SubgroupWidth64, SystemScope, WorkgroupCapability, WorkgroupLdsUninitialized,
    };

    #[test]
    fn source_terminals_fail_closed_on_host() {
        let workgroup = WorkgroupCapability::<'static, (), InitialEpoch> {
            size: 64,
            rank: 0,
            epoch: super::WorkgroupEpoch {
                _workgroup: PhantomData,
                _epoch: PhantomData,
                _not_send_sync: PhantomData,
            },
            _not_send_sync: PhantomData,
        };
        assert!(
            std::panic::catch_unwind(|| {
                let _ = workgroup.allocate_lds::<u32, 64>()
                    as super::WorkgroupLds<
                        '_,
                        u32,
                        64,
                        WorkgroupLdsUninitialized,
                        (),
                        InitialEpoch,
                    >;
            })
            .is_err()
        );
    }

    #[test]
    fn neutral_width_and_scope_markers_are_exact() {
        assert_eq!(<SubgroupWidth64 as crate::SubgroupWidth>::LANES, 64);
        let _ = core::mem::size_of::<SystemScope>();
    }
}
