pub(super) fn frame() -> std::result::Result<usize, Resource> {
    // Typed reached-carrier envelopes, not native stack or allocator metadata.
    let rows = [
        size_of::<RetainedSharedEngineV1<'static>>(),
        size_of::<(
            EnginePhase,
            Option<(&SemanticFunctionDeclV1, &[SemanticTypeDeclV1])>,
            RetainedAliasStateV1<'static>,
            liveness::RetainedSharedLivenessV1<'static>,
            Vec<AliasData>,
            BTreeSet<SemanticTransparentBorrowSiteV1>,
            BTreeSet<SemanticTransparentBorrowSiteV1>,
            usize,
            usize,
            usize,
            bool,
        )>(),
        size_of::<(
            Vec<Alias>,
            Option<Vec<Alias>>,
            Vec<u32>,
            Option<&SemanticRvalueV1>,
            Option<&SemanticStatementKindV1>,
            Option<&SemanticTerminatorKindV1>,
            Output,
            &Output,
        )>(),
        size_of::<(
            &mut RetainedSharedEngineV1<'static>,
            &RetainedSharedEngineV1<'static>,
            &mut RetainedAliasSessionV1<'static, 'static, 'static>,
            &mut RetainedAliasStateV1<'static>,
            &mut liveness::RetainedSharedLivenessV1<'static>,
        )>(),
        size_of::<(
            &'static SemanticPlaceV1,
            Path<'static>,
            Option<Path<'static>>,
            Result<Path<'static>>,
            Source<'static>,
            Option<Source<'static>>,
            Result<Source<'static>>,
            &model::SemanticAssignmentV1,
            Option<(u32, SemanticTypeIdV1, SemanticTypeIdV1)>,
            (u32, SemanticTypeIdV1, SemanticTypeIdV1),
        )>(),
        size_of::<(
            std::vec::IntoIter<Alias>,
            Option<std::vec::IntoIter<Alias>>,
            &mut std::vec::IntoIter<Alias>,
            Option<&mut std::vec::IntoIter<Alias>>,
            Result<&mut std::vec::IntoIter<Alias>>,
            Alias,
            Option<Alias>,
            Result<Alias>,
            &Alias,
            &mut Alias,
            Result<&Alias>,
            Result<&mut Alias>,
            Option<&Alias>,
            Option<&mut Alias>,
        )>(),
        size_of::<(
            Vec<Alias>,
            &Vec<Alias>,
            &mut Vec<Alias>,
            Option<Vec<Alias>>,
            Option<&Vec<Alias>>,
            Option<&mut Vec<Alias>>,
            Result<Vec<Alias>>,
            Result<&Vec<Alias>>,
            Result<&mut Vec<Alias>>,
            &mut Vec<u32>,
            &[u32],
        )>(),
        size_of::<(
            &SemanticRvalueV1,
            &SemanticRvalueKindV1,
            &SemanticOperandV1,
            &model::SemanticAggregateRvalueV1,
            model::SemanticAggregateKindV1,
            &model::SemanticAggregateKindV1,
            &model::SemanticTypeDeclV1,
            Option<&model::SemanticTypeDeclV1>,
            &SemanticTypeShapeV1,
            &model::SemanticAggregateTypeV1,
            &[SemanticTypeIdV1],
            Option<&[SemanticTypeIdV1]>,
            Option<&SemanticTypeIdV1>,
            &SemanticTypeIdV1,
            SemanticTypeIdV1,
        )>(),
        size_of::<(
            std::iter::Enumerate<std::slice::Iter<'static, SemanticOperandV1>>,
            std::slice::Iter<'static, SemanticOperandV1>,
            &[SemanticOperandV1],
            (usize, &SemanticOperandV1),
            &SemanticOperandV1,
            usize,
            bool,
        )>(),
        size_of::<(
            &SemanticFunctionDeclV1,
            &[SemanticTypeDeclV1],
            &[model::SemanticLocalDeclV1],
            &model::SemanticLocalDeclV1,
            Option<&model::SemanticLocalDeclV1>,
            model::SemanticLocalRoleV1,
            model::SemanticLocalIdV1,
            &model::SemanticLocalIdV1,
            model::SemanticTypeIdV1,
            u32,
            usize,
        )>(),
        size_of::<(
            &model::SemanticPointerTypeV1,
            model::SemanticPointerKindV1,
            model::SemanticMutabilityV1,
            model::SemanticPointerMetadataV1,
            model::SemanticBorrowKindV1,
            &model::SemanticBorrowKindV1,
            &[SemanticProjectionV1],
            std::slice::Iter<'static, SemanticProjectionV1>,
            &SemanticProjectionV1,
            SemanticProjectionKindV1,
        )>(),
        size_of::<(
            &model::SemanticCheckedBinaryRvalueV1,
            &model::SemanticUncheckedBinaryRvalueV1,
            &model::SemanticMemoryLoadV1,
            &model::SemanticMemoryStoreV1,
            &model::SemanticAtomicRmwV1,
            &model::SemanticAtomicCompareExchangeV1,
            &SemanticPlaceV1,
            &SemanticOperandV1,
        )>(),
        size_of::<(
            &SemanticStatementKindV1,
            &SemanticTerminatorKindV1,
            &model::SemanticDirectCallV1,
            &model::SemanticDirectTailCallV1,
            &model::SemanticAssertMessageV1,
            &[SemanticOperandV1],
            std::slice::Iter<'static, SemanticOperandV1>,
            &SemanticOperandV1,
        )>(),
        size_of::<(
            std::collections::btree_map::Iter<'static, u32, Vec<Alias>>,
            (&u32, &Vec<Alias>),
            &u32,
            u32,
            std::slice::Iter<'static, Alias>,
            &Alias,
            std::slice::IterMut<'static, Candidate>,
            &mut Candidate,
            &BTreeMap<u32, Vec<Alias>>,
            &mut Vec<Candidate>,
        )>(),
        size_of::<(
            std::iter::Enumerate<std::slice::Iter<'static, model::SemanticBasicBlockV1>>,
            &[model::SemanticBasicBlockV1],
            &model::SemanticBasicBlockV1,
            (usize, &model::SemanticBasicBlockV1),
            &model::SemanticTerminatorV1,
        )>(),
        size_of::<(
            std::iter::Enumerate<std::slice::Iter<'static, model::SemanticStatementV1>>,
            &[model::SemanticStatementV1],
            &model::SemanticStatementV1,
            (usize, &model::SemanticStatementV1),
            &SemanticStatementKindV1,
        )>(),
        size_of::<(
            SemanticTransparentBorrowSiteV1,
            &SemanticTransparentBorrowSiteV1,
            &mut BTreeSet<SemanticTransparentBorrowSiteV1>,
            &BTreeSet<SemanticTransparentBorrowSiteV1>,
            RetainedResult<&BTreeSet<SemanticTransparentBorrowSiteV1>>,
            Candidate,
            &Candidate,
            AliasData,
            Vec<AliasData>,
            &Vec<AliasData>,
            &mut Vec<AliasData>,
            (u32, Vec<Alias>),
        )>(),
        size_of::<(
            Result<()>,
            Result<bool>,
            Result<usize>,
            Error,
            Resource,
            RetainedAliasErrorV1,
            RetainedResult<()>,
            RetainedResult<usize>,
            liveness::RetainedLivenessErrorV1,
            std::result::Result<(), liveness::RetainedLivenessErrorV1>,
            std::result::Result<&liveness::Schedule, liveness::RetainedLivenessErrorV1>,
            &liveness::Schedule,
        )>(),
        size_of::<(
            std::result::Result<(), std::collections::TryReserveError>,
            std::collections::TryReserveError,
            std::result::Result<(), Resource>,
            std::result::Result<usize, Resource>,
            std::num::TryFromIntError,
            std::result::Result<u32, std::num::TryFromIntError>,
            Result<u32>,
            Option<usize>,
        )>(),
        size_of::<(
            &Budget<'static>,
            &mut Budget<'static>,
            &usize,
            &mut usize,
            Option<Resource>,
            &mut Option<Resource>,
            &mut Resource,
            &mut RetainedSharedObserverV1<'static>,
            RetainedAliasSessionV1<'static, 'static, 'static>,
            RetainedResult<RetainedAliasSessionV1<'static, 'static, 'static>>,
        )>(),
        size_of::<(
            Option<(&SemanticFunctionDeclV1, &[SemanticTypeDeclV1])>,
            std::result::Result<(&SemanticFunctionDeclV1, &[SemanticTypeDeclV1]), Resource>,
            &SemanticFunctionDeclV1,
            &[SemanticTypeDeclV1],
            usize,
            usize,
            usize,
            usize,
            usize,
            usize,
            usize,
            usize,
            u32,
            u32,
            bool,
            bool,
            bool,
            (usize, usize, usize),
        )>(),
        size_of::<(
            &mut RetainedAliasSessionV1<'static, 'static, 'static>,
            &SemanticOperandV1,
            &SemanticRvalueKindV1,
            &model::SemanticAssertMessageV1,
            &model::SemanticAggregateRvalueV1,
            Option<&[SemanticTypeIdV1]>,
            usize,
            bool,
            Result<()>,
            &mut Option<Resource>,
        )>(),
        size_of::<(
            &[bool],
            &mut super::super::super::super::shared_primitive_reads_v1::RetainedSharedRowsV1,
            &BTreeSet<SemanticTransparentBorrowSiteV1>,
            RetainedResult<()>,
            RetainedResult<&BTreeSet<SemanticTransparentBorrowSiteV1>>,
        )>(),
        liveness::retained_expiry::frame()?,
        size_of::<(
            [usize; 25],
            std::array::IntoIter<usize, 25>,
            usize,
            usize,
            std::result::Result<usize, Resource>,
            Resource,
        )>(),
    ];
    rows.into_iter().try_fold(0usize, |sum, bytes| {
        sum.checked_add(bytes).ok_or(Resource::Arithmetic)
    })
}
