#![forbid(unsafe_code)]
#![deny(missing_docs)]

//! Explicit, fail-closed routing for bounded compiler transactions.
//!
//! The driver invokes exactly one backend for a request's
//! [`PipelineSelectorV1`]. Backend failures and outputs that do not validate
//! against the original request become canonical rejected outputs. No route
//! can fall back to another compiler implementation.
//!
//! This crate grants no artifact publication, proof promotion, module loading,
//! dispatch, or launch authority and contains no COMGR integration.

use core::fmt;

use fe2o3_compiler_api::{
    CanonicalDiagnosticV1, CompileDispositionV1, CompileOutputV1, CompileRequestV1,
    DiagnosticCodeV1, DiagnosticMessageV1, DiagnosticSeverityV1, PipelineSelectorV1,
};

mod gemm_proof_required;
mod gemm_semantic_check;

pub use gemm_proof_required::{
    AdmittedGemmCompilerBackendV1, GEMM_REQUIRED_SAFETY_PROPERTIES_V1,
    GemmExpectedUnsafeObligationV1, GemmObligationFindingErrorV1, GemmObligationFindingV1,
    GemmObligationOriginV1, GemmObligationOutcomeV1, GemmProofDiagnosticV1,
    GemmProofEvaluationFailureV1, GemmProofRejectionKindV1, GemmProofReportErrorV1,
    GemmProofReportProviderV1, GemmProofReportV1, GemmProofRequirementsErrorV1,
    GemmProofRequirementsV1, GemmSafetyPropertyV1, MAX_GEMM_OBLIGATION_FINDINGS_V1,
    MAX_GEMM_UNSAFE_OBLIGATIONS_V1, ProofRequiredGemmAdmissionV1, ProofRequiredGemmBackendV1,
    admit_proof_required_gemm_v1,
};
pub use gemm_semantic_check::{
    GemmSemanticAnalysisErrorV1, GemmSemanticCheckingBackendV1, GemmSemanticCounterexampleV1,
    GemmSemanticProgramBindingErrorV1, GemmSemanticProgramV1, analyze_gemm_semantics_v1,
    general_gemm_semantic_obligation_set_identity_v1,
};

/// Bounded reason that a selected backend could not complete a transaction.
///
/// Source-program rejection should normally be represented by a validated
/// [`CompileOutputV1`] so its diagnostics and terminal receipt are preserved.
/// These variants describe failures where no backend output can be committed.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum CompilerBackendFailureV1 {
    /// The backend does not support the routed request.
    UnsupportedRequest,
    /// The selected backend is not available.
    Unavailable,
    /// The backend exhausted a request-bounded resource.
    ResourceExhausted,
    /// The backend failed without a valid transactional output.
    Internal,
}

impl fmt::Display for CompilerBackendFailureV1 {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(match self {
            Self::UnsupportedRequest => "selected compiler backend does not support the request",
            Self::Unavailable => "selected compiler backend is unavailable",
            Self::ResourceExhausted => {
                "selected compiler backend exhausted a request-bounded resource"
            }
            Self::Internal => "selected compiler backend failed without a valid transaction",
        })
    }
}

impl std::error::Error for CompilerBackendFailureV1 {}

/// Backend contract for one bounded, transactional compile attempt.
///
/// Implementations receive a bounded [`CompileRequestV1`] and may return only
/// a validated, bounded [`CompileOutputV1`] or a fixed-size failure reason.
/// Implementations must not publish, load, dispatch, or launch an executable
/// candidate as part of this call. A returned `Err` commits no partial output.
pub trait TransactionalCompilerBackendV1 {
    /// Executes one compile attempt for the request routed to this backend.
    fn compile_transaction(
        &mut self,
        request: &CompileRequestV1,
    ) -> Result<CompileOutputV1, CompilerBackendFailureV1>;
}

/// Driver contract for one bounded, fail-closed compiler transaction.
pub trait TransactionalCompilerDriverV1 {
    /// Routes one request and returns either its validated output or a canonical
    /// rejected output generated by the driver.
    fn compile_transaction(&mut self, request: &CompileRequestV1) -> CompileOutputV1;
}

/// Stable driver-owned diagnostic emitted for a fail-closed rejection.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
#[repr(u32)]
pub enum DriverDiagnosticV1 {
    /// The selected backend did not support the routed request.
    BackendUnsupportedRequest = 0x4644_0001,
    /// The selected backend was unavailable.
    BackendUnavailable = 0x4644_0002,
    /// The selected backend exhausted a request-bounded resource.
    BackendResourceExhausted = 0x4644_0003,
    /// The selected backend failed without a valid transaction.
    BackendInternalFailure = 0x4644_0004,
    /// The backend output named a different request commitment.
    OutputRequestMismatch = 0x4644_0010,
    /// The backend output named a different selector.
    OutputSelectorMismatch = 0x4644_0011,
    /// The backend output failed validation against the routed request.
    InvalidBackendOutput = 0x4644_0012,
    /// A `PlironShadow` backend attempted to return an executable candidate.
    ShadowCandidateProhibited = 0x4644_0013,
}

impl DriverDiagnosticV1 {
    /// Returns the stable numeric diagnostic code.
    pub const fn code(self) -> u32 {
        self as u32
    }

    const fn from_backend_failure(failure: CompilerBackendFailureV1) -> Self {
        match failure {
            CompilerBackendFailureV1::UnsupportedRequest => Self::BackendUnsupportedRequest,
            CompilerBackendFailureV1::Unavailable => Self::BackendUnavailable,
            CompilerBackendFailureV1::ResourceExhausted => Self::BackendResourceExhausted,
            CompilerBackendFailureV1::Internal => Self::BackendInternalFailure,
        }
    }

    const fn message(self) -> &'static str {
        match self {
            Self::BackendUnsupportedRequest => {
                "selected compiler backend does not support the routed request"
            }
            Self::BackendUnavailable => "selected compiler backend is unavailable",
            Self::BackendResourceExhausted => {
                "selected compiler backend exhausted a request-bounded resource"
            }
            Self::BackendInternalFailure => {
                "selected compiler backend failed without a valid transaction"
            }
            Self::OutputRequestMismatch => {
                "selected compiler backend returned a different request identity"
            }
            Self::OutputSelectorMismatch => {
                "selected compiler backend returned a different pipeline selector"
            }
            Self::InvalidBackendOutput => {
                "selected compiler backend returned an invalid transaction"
            }
            Self::ShadowCandidateProhibited => {
                "PlironShadow backend attempted to return an executable candidate"
            }
        }
    }
}

/// Compiler driver with one isolated backend slot per explicit selector.
///
/// Routing is a total match over [`PipelineSelectorV1`]. An error from the
/// selected slot is terminal and never causes another slot to be invoked.
#[derive(Clone, Debug)]
pub struct ExplicitPipelineDriverV1<Legacy, Shadow, Pliron> {
    legacy: Legacy,
    pliron_shadow: Shadow,
    pliron_v1: Pliron,
}

impl<Legacy, Shadow, Pliron> ExplicitPipelineDriverV1<Legacy, Shadow, Pliron> {
    /// Configures one backend for each explicit V1 selector.
    pub const fn new(legacy: Legacy, pliron_shadow: Shadow, pliron_v1: Pliron) -> Self {
        Self {
            legacy,
            pliron_shadow,
            pliron_v1,
        }
    }

    /// Returns a shared reference to the `Legacy` backend slot.
    pub const fn legacy_backend(&self) -> &Legacy {
        &self.legacy
    }

    /// Returns a shared reference to the `PlironShadow` backend slot.
    pub const fn pliron_shadow_backend(&self) -> &Shadow {
        &self.pliron_shadow
    }

    /// Returns a shared reference to the `PlironV1` backend slot.
    pub const fn pliron_v1_backend(&self) -> &Pliron {
        &self.pliron_v1
    }

    /// Returns mutable access to all three isolated backend slots.
    pub fn backends_mut(&mut self) -> (&mut Legacy, &mut Shadow, &mut Pliron) {
        (
            &mut self.legacy,
            &mut self.pliron_shadow,
            &mut self.pliron_v1,
        )
    }
}

impl<Legacy, Shadow, Pliron> TransactionalCompilerDriverV1
    for ExplicitPipelineDriverV1<Legacy, Shadow, Pliron>
where
    Legacy: TransactionalCompilerBackendV1,
    Shadow: TransactionalCompilerBackendV1,
    Pliron: TransactionalCompilerBackendV1,
{
    fn compile_transaction(&mut self, request: &CompileRequestV1) -> CompileOutputV1 {
        let result = match request.selector() {
            PipelineSelectorV1::Legacy => self.legacy.compile_transaction(request),
            PipelineSelectorV1::PlironShadow => self.pliron_shadow.compile_transaction(request),
            PipelineSelectorV1::PlironV1 => self.pliron_v1.compile_transaction(request),
        };

        match result {
            Ok(output) => validate_backend_output(request, output)
                .unwrap_or_else(|reason| rejected_output(request, reason)),
            Err(failure) => {
                rejected_output(request, DriverDiagnosticV1::from_backend_failure(failure))
            }
        }
    }
}

fn validate_backend_output(
    request: &CompileRequestV1,
    output: CompileOutputV1,
) -> Result<CompileOutputV1, DriverDiagnosticV1> {
    if request.selector() == PipelineSelectorV1::PlironShadow && output.candidate().is_some() {
        return Err(DriverDiagnosticV1::ShadowCandidateProhibited);
    }
    if output.request_identity() != request.identity() {
        return Err(DriverDiagnosticV1::OutputRequestMismatch);
    }
    if output.selector() != request.selector() {
        return Err(DriverDiagnosticV1::OutputSelectorMismatch);
    }

    CompileOutputV1::new(
        request,
        output.disposition(),
        output.snapshots().to_vec(),
        output.receipts().to_vec(),
        output.diagnostics().to_vec(),
        output.candidate().cloned(),
    )
    .map_err(|_| DriverDiagnosticV1::InvalidBackendOutput)
}

fn rejected_output(request: &CompileRequestV1, reason: DriverDiagnosticV1) -> CompileOutputV1 {
    let code = DiagnosticCodeV1::new(reason.code())
        .expect("driver diagnostic codes are statically nonzero");
    let message = DiagnosticMessageV1::new(reason.message())
        .expect("driver diagnostic messages are statically canonical and bounded");
    let diagnostic =
        CanonicalDiagnosticV1::new(0, code, DiagnosticSeverityV1::Error, None, None, message);

    CompileOutputV1::new(
        request,
        CompileDispositionV1::Rejected,
        Vec::new(),
        Vec::new(),
        vec![diagnostic],
        None,
    )
    .expect("a checked request always admits one fixed driver rejection diagnostic")
}
