cmake_minimum_required(VERSION 3.20)

if(DEFINED CASE)
  include("${HELPER}")
  fe2o3_gfx950_provider_profile("${CASE}")
  return()
endif()

set(HELPER "${CMAKE_CURRENT_LIST_DIR}/../cmake/Gfx950ProviderProfile.cmake")
include("${HELPER}")
foreach(VERSION IN ITEMS 7.2.1 7.2.4)
  fe2o3_gfx950_provider_profile("rocm-${VERSION}")
  file(STRINGS "${CMAKE_CURRENT_LIST_DIR}/../../../examples/gfx950_low_precision/gfx950-ocml-rocm-${VERSION}.manifest" EXPECTED)
  list(SUBLIST EXPECTED 4 9 EXPECTED_FILES)
  list(LENGTH FE2O3_GFX950_DEVICE_LIB_FILES COUNT)
  list(LENGTH FE2O3_GFX950_DEVICE_LIB_SHA256 DIGEST_COUNT)
  if(NOT COUNT EQUAL 9 OR NOT DIGEST_COUNT EQUAL 9 OR
     NOT FE2O3_GFX950_DEFAULT_DEVICE_LIB_DIR STREQUAL "/opt/rocm-${VERSION}/lib/llvm/lib/clang/22/lib/amdgcn/bitcode")
    message(FATAL_ERROR "reviewed whole-profile shape mismatch")
  endif()
  foreach(INDEX RANGE 8)
    list(GET FE2O3_GFX950_DEVICE_LIB_FILES ${INDEX} NAME)
    list(GET FE2O3_GFX950_DEVICE_LIB_SHA256 ${INDEX} DIGEST)
    list(GET EXPECTED_FILES ${INDEX} ROW)
    if(NOT ROW STREQUAL "${NAME}=${DIGEST}")
      message(FATAL_ERROR "selected profile differs from independent manifest")
    endif()
  endforeach()
endforeach()

foreach(UNKNOWN IN ITEMS rocm-7.2.2 rocm-7.2.4-mixed auto)
  execute_process(COMMAND "${CMAKE_COMMAND}" "-DCASE=${UNKNOWN}"
    "-DHELPER=${HELPER}" -P "${CMAKE_CURRENT_LIST_FILE}"
    RESULT_VARIABLE RESULT OUTPUT_VARIABLE OUTPUT ERROR_VARIABLE ERROR
    TIMEOUT 5)
  if(RESULT EQUAL 0 OR NOT ERROR MATCHES "unknown gfx950 device-library profile")
    message(FATAL_ERROR "unknown provider profile did not refuse")
  endif()
endforeach()

if(NOT DEFINED TEST_BINARY_DIR)
  message(FATAL_ERROR "TEST_BINARY_DIR must name the owned test directory")
endif()
string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef SUFFIX)
set(OWN "${TEST_BINARY_DIR}/gfx950-profile-${SUFFIX}")
set(COPIED_HELPER "${OWN}/tools/fe2o3-llvm-link-worker/cmake/Gfx950ProviderProfile.cmake")
set(COPIED_MANIFEST "${OWN}/examples/gfx950_low_precision/gfx950-ocml-rocm-7.2.4.manifest")
file(MAKE_DIRECTORY "${OWN}/tools/fe2o3-llvm-link-worker/cmake" "${OWN}/examples/gfx950_low_precision")
configure_file("${HELPER}" "${COPIED_HELPER}" COPYONLY)
file(READ "${CMAKE_CURRENT_LIST_DIR}/../../../examples/gfx950_low_precision/gfx950-ocml-rocm-7.2.4.manifest" ORIGINAL)
foreach(MUTATION IN ITEMS mixed renamed extra)
  if(MUTATION STREQUAL "mixed")
    string(REPLACE "cfe97fe9ee29379f522e5f20ae55aae1cdb96eb41d6aa250ea11c4941c54e019"
      "2e3451857fcf47b931c5c5a29e9c42a6ddc3099c8359079441a9a06a217ead7e" MODIFIED "${ORIGINAL}")
  elseif(MUTATION STREQUAL "renamed")
    string(REPLACE "rocm_version=7.2.4" "rocm_version=7.2.1" MODIFIED "${ORIGINAL}")
  else()
    set(MODIFIED "${ORIGINAL}extra=unreviewed\n")
  endif()
  file(WRITE "${COPIED_MANIFEST}" "${MODIFIED}")
  execute_process(COMMAND "${CMAKE_COMMAND}" -DCASE=rocm-7.2.4
    "-DHELPER=${COPIED_HELPER}" -P "${CMAKE_CURRENT_LIST_FILE}"
    RESULT_VARIABLE RESULT OUTPUT_VARIABLE OUTPUT ERROR_VARIABLE ERROR
    TIMEOUT 5)
  if(RESULT EQUAL 0 OR NOT ERROR MATCHES "reviewed whole-profile manifest mismatch")
    message(FATAL_ERROR "substituted provider manifest did not refuse")
  endif()
endforeach()
file(REMOVE_RECURSE "${OWN}")
message(STATUS "gfx950 profile controls: two complete profiles, three unknown and three substituted profiles passed")
