//! Registered CPU obligations on the same independently emitted original trace.
use super::super::invocations::InvocationPlan;
use super::{
    Error, Resource, Result, Writer, reference_expressions as expressions, slots::SourceSlots,
};
use crate::{SourceScalarReferenceInputV69 as Input, portable_reference_v1::*};
use fe2o3_kernel_ir::{ExplicitLaunchExtent, FormalIndexWidth};
use fe2o3_mir_model::semantic_mir_v1::{SemanticFunctionDeclV1, SemanticLocalRoleV1};
use sha2::{Digest, Sha256};
use std::{
    fmt::Write as _,
    mem::{align_of, size_of},
};

const COVERAGE: &str = include_str!("original_semantic_mir_reference_coverage_v69.vrs");

#[cfg(test)]
#[path = "original_semantic_mir_reference_consumer_v69_tests.rs"]
mod tests;

fn refused() -> Error {
    Error::Statement("registered reference requires a closed scalar Index1D point contract")
}

fn field(hash: &mut Sha256, bytes: &[u8]) -> Result<()> {
    hash.update(
        u64::try_from(bytes.len())
            .map_err(|_| Resource::Arithmetic)?
            .to_le_bytes(),
    );
    hash.update(bytes);
    Ok(())
}

fn check_kernel(
    input: &Input<'_>,
    body: &SemanticFunctionDeclV1,
    out: &mut Writer<'_, '_>,
) -> Result<()> {
    let kernel = &input.kernel;
    out.budget.charge_work(5 * 32 + 4)?;
    if body.identity().as_bytes() != &kernel.function_sha256
        || body.item_definition_identity().as_bytes() != &kernel.item_definition_sha256
        || body.monomorphization_identity().as_bytes() != &kernel.monomorphization_sha256
        || body.generic_type_arguments_identity().as_bytes()
            != &kernel.generic_type_arguments_sha256
        || body.const_generic_arguments_identity().as_bytes()
            != &kernel.const_generic_arguments_sha256
        || body.abi().source_input_types().len()
            != input.replay.signature_preimage.kernel_inputs().len()
    {
        return Err(refused());
    }
    let domain = b"fe2o3/semantic-mir/rustc-local/v1";
    out.budget.charge_work(
        body.locals()
            .len()
            .checked_add(4 * 8 + domain.len() + 32 + 32 + 4 + 32)
            .ok_or(Resource::Arithmetic)?,
    )?;
    let mut returns = body
        .locals()
        .iter()
        .filter(|local| local.role() == SemanticLocalRoleV1::Return);
    let original = returns.next().ok_or_else(refused)?;
    if returns.next().is_some() {
        return Err(refused());
    }
    let mut hash = Sha256::new();
    let raw_return = 0u32.to_le_bytes();
    for bytes in [
        domain.as_slice(),
        kernel.function_sha256.as_slice(),
        kernel.rustc_mir_body_sha256.as_slice(),
        raw_return.as_slice(),
    ] {
        field(&mut hash, bytes)?;
    }
    let identity: [u8; 32] = hash.finalize().into();
    if original.identity().as_bytes() != &identity {
        return Err(refused());
    }
    Ok(())
}

pub(super) fn emit(
    relation: &fe2o3_lower_mir_kernel::ProductionSourceCorrespondenceV18<'_>,
    plan: &InvocationPlan<'_, '_>,
    slots: &SourceSlots<'_, '_>,
    references: &[Input<'_>],
    launches: &[ExplicitLaunchExtent],
    width: FormalIndexWidth,
    out: &mut Writer<'_, '_>,
) -> Result<()> {
    // Preserve historical generated bytes, including whitespace, exactly.
    if references.is_empty() {
        return Ok(());
    }
    out.budget.reserve_storage(headers())?;
    let source = relation.source(out.budget)?;
    if !std::ptr::eq(source, plan.source(out)?) {
        return Err(refused());
    }
    let roots = source.root_count(out.budget)?;
    out.budget.charge_work(
        roots
            .checked_add(references.len())
            .ok_or(Resource::Arithmetic)?,
    )?;
    if references.len() > roots || launches.len() != roots {
        return Err(refused());
    }
    let index_bits = match width {
        FormalIndexWidth::Bits32 => 32,
        FormalIndexWidth::Bits64 => 64,
        _ => return Err(refused()),
    };
    let mut seen = super::vector(roots, out)?;
    seen.resize(roots, false);
    write!(out, "{COVERAGE}\n").map_err(|_| out.error())?;
    for input in references {
        out.budget.charge_work(4)?;
        let root = input.original_root;
        let slot = seen.get_mut(root).ok_or_else(refused)?;
        if *slot
            || !matches!(
                launches.get(root),
                Some(ExplicitLaunchExtent::Exact { rank: 1, .. })
            )
        {
            return Err(refused());
        }
        *slot = true;
        let (function, _) = source.root(root, out.budget)?;
        let semantic = source.source_semantic(out.budget)?;
        out.budget
            .charge_work(semantic.canonical_encoding().len())?;
        let selected = semantic
            .select_kernel_body_for_root_v1(function)
            .ok_or_else(refused)?;
        let body = semantic
            .functions()
            .get(selected.body().index() as usize)
            .ok_or_else(refused)?;
        let entry = semantic
            .functions()
            .get(function.index() as usize)
            .ok_or_else(refused)?;
        check_kernel(input, body, out)?;
        out.budget
            .charge_work(body.abi().source_input_types().len())?;
        if body.abi().source_input_types() != entry.abi().source_input_types() {
            return Err(refused());
        }
        let mut fuel = 1usize;
        for instance in 0..plan.root(root, out)?.instances.len() {
            let instance = plan.instance(root, instance, out)?;
            if instance.active {
                fuel = fuel
                    .checked_add(
                        instance
                            .blocks
                            .len()
                            .checked_mul(2)
                            .ok_or(Resource::Arithmetic)?,
                    )
                    .ok_or(Resource::Arithmetic)?;
            }
        }
        // Move, rather than copy, the already funded output buffer through the
        // independently owned replay scope. No replay borrow escapes the call.
        let text = std::mem::take(&mut out.text);
        let failure = out.failure.take();
        let replay = ReferenceReplayInputV1 {
            signature_preimage: input.replay.signature_preimage,
            effect_ir: input.replay.effect_ir,
            effect_ir_sha256: input.replay.effect_ir_sha256,
            observable_output_writes: input.replay.observable_output_writes,
        };
        let result = with_replayed_output_writes_v1(replay, out.budget, |cpu, budget| {
            let mut nested = Writer {
                text,
                budget,
                failure,
            };
            let result = emit_root(input, body, slots, cpu, index_bits, fuel, &mut nested);
            (nested.text, nested.failure, result)
        });
        // Replay errors retain the original sticky resource denial before their
        // descriptive CPU error is mapped to the closed statement refusal.
        out.budget.check_prior_denials_v1()?;
        let (text, failure, result) = result.map_err(|_| refused())?;
        out.text = text;
        out.failure = failure;
        result?;
        source.check_query_v18(out.budget)?;
    }
    Ok(())
}

fn emit_root(
    input: &Input<'_>,
    body: &SemanticFunctionDeclV1,
    slots: &SourceSlots<'_, '_>,
    cpu: &ReplayedCpuEffectsV1,
    index_bits: u32,
    fuel: usize,
    out: &mut Writer<'_, '_>,
) -> Result<()> {
    use ReferenceArgumentRelationV1 as Relation;
    let root = input.original_root;
    let ir = input.replay.effect_ir;
    let signature = input.replay.signature_preimage;
    if !cpu.bounds.is_empty()
        || cpu.writes.is_empty()
        || ir.point_coordinate_count_v1().map_err(|_| refused())? != 1
    {
        return Err(refused());
    }
    out.budget.charge_work(ir.blocks.len())?;
    if !closed_control(ir) {
        return Err(refused());
    }
    let context = expressions::Context {
        signature,
        relations: &ir.relations,
        index_bits,
        rank: 1,
    };
    let mut outputs = 0usize;
    out.budget.charge_work(ir.relations.len())?;
    for relation in &ir.relations {
        match relation {
            Relation::DisjointOutputCoordinate { argument, element } => {
                let ty = *body
                    .abi()
                    .source_input_types()
                    .get(*argument as usize)
                    .ok_or_else(refused)?;
                let class = slots.descriptor_slice_class(ty, out)?.ok_or_else(refused)?;
                if !class.writable
                    || !class.exclusive
                    || class.metadata_bits != index_bits
                    || class.element != scalar_type(*element)?
                {
                    return Err(refused());
                }
                outputs = outputs.checked_add(1).ok_or(Resource::Arithmetic)?;
            }
            Relation::PointCoordinate { axis: 0, .. }
            | Relation::ScalarInput { .. }
            | Relation::SharedSliceInput { .. } => {}
            _ => return Err(refused()),
        }
    }
    if outputs == 0 {
        return Err(refused());
    }
    // Both function identities and original body commitments are transcript
    // inputs, not executable constants or assumptions available to the solver.
    write!(out, "// registered-reference-v69 root={root} kernel=").map_err(|_| out.error())?;
    identity(&input.kernel, out)?;
    write!(out, " reference=").map_err(|_| out.error())?;
    identity(&input.reference, out)?;
    write!(out, " ir=").map_err(|_| out.error())?;
    for byte in input.replay.effect_ir_sha256 {
        write!(out, "{byte:02x}").map_err(|_| out.error())?;
    }
    write!(out, "\nspec fn invocation_reference_domain_{root}_v69(arguments: Seq<MemoryValueV30>, external: ByteMemoryV30, execution: MemoryExecutionContextV37) -> bool {{\n invocation_paired_native_inputs_{root}_v38(arguments, external, execution) && execution.rank == 1\n").map_err(|_| out.error())?;
    for relation in &ir.relations {
        if let Relation::DisjointOutputCoordinate { argument, element } = relation {
            let width = expressions::bits(*element, index_bits)?.div_ceil(8);
            write!(out, " && (match arguments[{argument}int] {{ MemoryValueV30::Slice(slice) => slice.length == 0 || byte_range_aligned_v30(external, slice.pointer, slice.length * {width}int, {width}int), _ => false }})\n").map_err(|_| out.error())?;
        }
    }
    // Aliasing is forbidden by the registered disjoint output carrier, not by
    // a desired equality of effects. Shared input/output regions stay separate.
    for (i, left) in ir.relations.iter().enumerate() {
        let Relation::DisjointOutputCoordinate {
            argument: left,
            element: le,
        } = left
        else {
            continue;
        };
        for (j, right) in ir.relations.iter().enumerate() {
            out.budget.charge_work(1)?;
            let (right, re) = match right {
                Relation::DisjointOutputCoordinate { argument, element } if i < j => {
                    (*argument, *element)
                }
                Relation::SharedSliceInput { argument, element } => (*argument, *element),
                _ => continue,
            };
            let lw = expressions::bits(*le, index_bits)?.div_ceil(8);
            let rw = expressions::bits(re, index_bits)?.div_ceil(8);
            write!(out, " && (match (arguments[{left}int], arguments[{right}int]) {{ (MemoryValueV30::Slice(left), MemoryValueV30::Slice(right)) => left.length == 0 || right.length == 0 || left.pointer.allocation != right.pointer.allocation || left.pointer.byte_offset + left.length * {lw}int <= right.pointer.byte_offset || right.pointer.byte_offset + right.length * {rw}int <= left.pointer.byte_offset, _ => false }})\n").map_err(|_| out.error())?;
        }
    }
    write!(out, "}}\nspec fn invocation_reference_computations_{root}_v69(arguments: Seq<MemoryValueV30>, external: ByteMemoryV30, execution: MemoryExecutionContextV37) -> bool {{\n true").map_err(|_| out.error())?;
    for value in &cpu.values {
        out.budget.charge_work(1)?;
        // The authenticated Unit return is a real defined CPU computation,
        // but never a scalar output value or an operand of scalar arithmetic.
        if matches!(
            value.expression,
            ReferenceEffectExpressionV1::Constant(ReferenceConstantV1::ZeroSized)
        ) {
            write!(out, " && MemoryValueV30::Unit == MemoryValueV30::Unit\n")
                .map_err(|_| out.error())?;
            continue;
        }
        write!(out, " && ({{ let value = ").map_err(|_| out.error())?;
        let scalar = context.expression(&value.expression, out)?;
        let bits = expressions::bits(scalar, index_bits)?;
        write!(
            out,
            "; invocation_source_byte_value_typed_v36(value, {bits}int) }})\n"
        )
        .map_err(|_| out.error())?;
    }
    write!(out, "}}\nspec fn invocation_reference_active_count_{root}_v69(arguments: Seq<MemoryValueV30>, execution: MemoryExecutionContextV37) -> nat {{\n let point = byte_execution_index_v37(execution, 0int, 0int);\n 0nat").map_err(|_| out.error())?;
    for relation in &ir.relations {
        out.budget.charge_work(1)?;
        if let Relation::DisjointOutputCoordinate { argument, .. } = relation {
            write!(out, " + (if invocation_reference_point_active_v69(arguments[{argument}int], point) {{ 1nat }} else {{ 0nat }})\n").map_err(|_| out.error())?;
        }
    }
    write!(out, "}}\nspec fn invocation_reference_expected_{root}_v69(arguments: Seq<MemoryValueV30>, external: ByteMemoryV30, execution: MemoryExecutionContextV37) -> Seq<InvocationReferenceOutputV69> {{\n let point = byte_execution_index_v37(execution, 0int, 0int);\n let outputs: Seq<InvocationReferenceOutputV69> = seq![];\n").map_err(|_| out.error())?;
    for write in &cpu.writes {
        out.budget.charge_work(4)?;
        let ReferenceOutputCoordinateV1::LogicalPoint(point) = &write.coordinate else {
            return Err(refused());
        };
        if point.as_ref() != [ReferenceEffectExpressionV1::PointCoordinate { axis: 0 }] {
            return Err(refused());
        }
        let mut matches = ir.relations.iter().filter_map(|relation| match relation {
            Relation::DisjointOutputCoordinate { argument, element }
                if *argument == write.argument =>
            {
                Some(*element)
            }
            _ => None,
        });
        out.budget.charge_work(ir.relations.len())?;
        let element = matches.next().ok_or_else(refused)?;
        if matches.next().is_some() {
            return Err(refused());
        }
        let argument = write.argument;
        write!(out, " let outputs = outputs + if invocation_reference_point_active_v69(arguments[{argument}int], point) && ").map_err(|_| out.error())?;
        context.predicate(&write.guard, out)?;
        write!(out, " {{ let value = ").map_err(|_| out.error())?;
        if context.expression(&write.rhs, out)? != element {
            return Err(refused());
        }
        let width = expressions::bits(element, index_bits)?.div_ceil(8);
        let argument = write.argument;
        write!(out, "; match arguments[{argument}int] {{ MemoryValueV30::Slice(slice) => seq![InvocationReferenceOutputV69 {{ argument: {argument}int, address: MemoryPointerV30 {{ byte_offset: slice.pointer.byte_offset + point * {width}int, ..slice.pointer }}, width: {width}int, alignment: {width}int, value }}], _ => seq![] }} }} else {{ seq![] }};\n").map_err(|_| out.error())?;
    }
    write!(out, " outputs\n}}\nspec fn invocation_reference_source_trace_{root}_v69(arguments: Seq<MemoryValueV30>, external: ByteMemoryV30, execution: MemoryExecutionContextV37) -> CfgTraceV26<InvocationSourceByteStateV36, InvocationSourceEffectObservationV39> {{ cfg_trace_v26(|s| invocation_paired_source_step_{root}_v36(s), invocation_source_initial_runtime_{root}_v36(arguments, external, execution), {fuel}nat) }}\n").map_err(|_| out.error())?;
    write!(out, "proof fn invocation_reference_complete_source_{root}_v69(arguments: Seq<MemoryValueV30>, external: ByteMemoryV30, execution: MemoryExecutionContextV37)\n requires invocation_reference_domain_{root}_v69(arguments, external, execution),\n ensures invocation_reference_computations_{root}_v69(arguments, external, execution),\n invocation_paired_source_defined_{root}_v36(invocation_source_initial_runtime_{root}_v36(arguments, external, execution), {fuel}nat),\n invocation_reference_source_trace_{root}_v69(arguments, external, execution).halted,\n invocation_reference_source_trace_{root}_v69(arguments, external, execution).state.machine.valid,\n invocation_reference_source_trace_{root}_v69(arguments, external, execution).state.machine.pc == -1,\n invocation_reference_expected_{root}_v69(arguments, external, execution).len() == invocation_reference_active_count_{root}_v69(arguments, execution),\n invocation_reference_complete_outputs_v69(invocation_reference_source_trace_{root}_v69(arguments, external, execution).events, invocation_reference_expected_{root}_v69(arguments, external, execution)),\n{{\n reveal_with_fuel(cfg_trace_v26, {});\n reveal_with_fuel(invocation_paired_source_defined_{root}_v36, {});\n}}\n", fuel.checked_add(1).ok_or(Resource::Arithmetic)?, fuel.checked_add(1).ok_or(Resource::Arithmetic)?).map_err(|_| out.error())?;
    write!(out, "proof fn invocation_reference_complete_final_{root}_v69(arguments: Seq<MemoryValueV30>, external: ByteMemoryV30, execution: MemoryExecutionContextV37)\n requires invocation_reference_domain_{root}_v69(arguments, external, execution),\n ensures invocation_reference_complete_outputs_v69(invocation_reference_source_trace_{root}_v69(arguments, external, execution).events, invocation_reference_expected_{root}_v69(arguments, external, execution)),\n cfg_trace_v26(|s| typed_final_actual_step_{root}_v49(s), typed_final_actual_initial_{root}_v49(arguments, external, execution).cursor, {fuel}nat).halted,\n invocation_paired_observations_related_{root}_v39(invocation_reference_source_trace_{root}_v69(arguments, external, execution).events, cfg_trace_v26(|s| typed_final_actual_step_{root}_v49(s), typed_final_actual_initial_{root}_v49(arguments, external, execution).cursor, {fuel}nat).events),\n{{ invocation_reference_complete_source_{root}_v69(arguments, external, execution);\n typed_final_native_source_trace_{root}_v49(arguments, external, execution, {fuel}nat);\n}}\n").map_err(|_| out.error())?;
    Ok(())
}

// Eligibility only: the independent replay separately proves contiguous
// identities, in-range successors and acyclicity before this is consulted.
fn closed_control(ir: &ReferenceEffectIrV1) -> bool {
    ir.loop_summaries.is_empty()
        && !ir.blocks.is_empty()
        && ir.blocks.iter().all(|block| {
            matches!(
                block.terminator,
                ReferenceTerminatorV1::Return | ReferenceTerminatorV1::Goto { .. }
            )
        })
}

fn scalar_type(scalar: ReferenceScalarTypeV1) -> Result<fe2o3_kernel_ir::ScalarType> {
    use ReferenceScalarTypeV1 as S;
    use fe2o3_kernel_ir::ScalarType as T;
    Ok(match scalar {
        S::U8 => T::U8,
        S::U16 => T::U16,
        S::U32 => T::U32,
        S::U64 => T::U64,
        S::I8 => T::I8,
        S::I16 => T::I16,
        S::I32 => T::I32,
        S::I64 => T::I64,
        S::F32 => T::F32,
        S::F64 => T::F64,
        _ => return Err(refused()),
    })
}

fn identity(value: &ReferenceFunctionIdentityV1, out: &mut Writer<'_, '_>) -> Result<()> {
    for field in [
        value.def_path_hash.as_slice(),
        value.function_sha256.as_slice(),
        value.item_definition_sha256.as_slice(),
        value.monomorphization_sha256.as_slice(),
        value.generic_type_arguments_sha256.as_slice(),
        value.const_generic_arguments_sha256.as_slice(),
        value.rustc_mir_body_sha256.as_slice(),
    ] {
        for byte in field {
            write!(out, "{byte:02x}").map_err(|_| out.error())?;
        }
    }
    Ok(())
}

fn headers() -> usize {
    size_of::<Sha256>()
        + align_of::<Sha256>()
        + size_of::<[&[u8]; 4]>()
        + 36
        + size_of::<Vec<bool>>()
        + size_of::<ReplayedCpuEffectsV1>()
        + size_of::<ReferenceReplayInputV1<'_>>()
        + size_of::<(String, Option<Resource>, Result<()>)>()
        + size_of::<expressions::Context<'_>>()
        + 16 * size_of::<&()>()
        + 16 * size_of::<usize>()
}
