#!/usr/bin/env python3
"""Generate the shared Rust and Verus constants for Formal Compiler V3."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import sys


ROOT = Path(__file__).resolve().parent.parent
SPEC = ROOT / "formal/compiler-v3/guarded-u32-xor-helper-store-v1.json"
RUST = ROOT / "crates/fe2o3-lower-mir-kernel/src/formal_compiler_v3_spec_generated.rs"
VERUS = ROOT / "crates/fe2o3-lower-mir-kernel/verus/formal_compiler_v3_spec_generated.rs"

EXPECTED_KEYS = {
    "schema_version",
    "claim_version",
    "claim_name",
    "word_bits",
    "byte_width",
    "byte_order",
    "helper_parameters",
    "branch_arms",
    "maximum_call_depth",
    "minimum_loop_trip_count",
    "maximum_loop_trip_count",
    "readonly_accesses",
    "disjoint_writes",
    "dynamic_extent",
    "scalar_operations",
}


def load_spec(path: Path = SPEC) -> dict[str, object]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict) or set(value) != EXPECTED_KEYS:
        raise ValueError("V3 spec must contain the exact closed key set")
    integers = (
        "schema_version",
        "claim_version",
        "word_bits",
        "byte_width",
        "helper_parameters",
        "branch_arms",
        "maximum_call_depth",
        "minimum_loop_trip_count",
        "maximum_loop_trip_count",
        "readonly_accesses",
        "disjoint_writes",
    )
    if any(type(value[key]) is not int or value[key] <= 0 for key in integers):
        raise ValueError("V3 integer fields must be positive integers")
    if value["schema_version"] != 1 or value["claim_version"] != 3:
        raise ValueError("unsupported V3 spec version")
    if not isinstance(value["claim_name"], str) or re.fullmatch(
        r"[a-z][a-z0-9-]{0,63}", value["claim_name"]
    ) is None:
        raise ValueError("V3 claim name is not canonical")
    if value["word_bits"] != value["byte_width"] * 8:
        raise ValueError("word width must equal the byte width")
    if value["byte_order"] != "little" or value["dynamic_extent"] is not True:
        raise ValueError("V3 closes byte order and extent mode")
    if value["minimum_loop_trip_count"] > value["maximum_loop_trip_count"]:
        raise ValueError("invalid V3 loop interval")
    operations = value["scalar_operations"]
    if not isinstance(operations, list) or not operations:
        raise ValueError("V3 scalar operation roster must be nonempty")
    if any(not isinstance(item, str) or not item for item in operations):
        raise ValueError("V3 scalar operation names must be nonempty strings")
    if operations != sorted(set(operations)):
        raise ValueError("V3 scalar operation roster must be unique and sorted")
    return value


def render_rust(spec: dict[str, object]) -> str:
    operations = "\n".join(
        f'    ("{item}", {tag}),'
        for tag, item in enumerate(spec["scalar_operations"], start=1)
    )
    return f'''// @generated by scripts/generate-formal-compiler-v3-spec.py; do not edit.

/// Declarative V3 manifest schema version.
pub const FORMAL_COMPILER_V3_SCHEMA_VERSION: u16 = {spec["schema_version"]};
/// Formal Compiler claim generation.
pub const FORMAL_COMPILER_V3_CLAIM_VERSION: u16 = {spec["claim_version"]};
/// Stable name of the exact composed V3 fragment.
pub const FORMAL_COMPILER_V3_CLAIM_NAME: &str = "{spec["claim_name"]}";
/// Closed scalar word width.
pub const FORMAL_COMPILER_V3_WORD_BITS: u16 = {spec["word_bits"]};
/// Closed typed access width in bytes.
pub const FORMAL_COMPILER_V3_BYTE_WIDTH: u8 = {spec["byte_width"]};
/// Exact helper parameter count.
pub const FORMAL_COMPILER_V3_HELPER_PARAMETERS: u8 = {spec["helper_parameters"]};
/// Exact helper branch-arm count.
pub const FORMAL_COMPILER_V3_BRANCH_ARMS: u8 = {spec["branch_arms"]};
/// Maximum depth modeled by the bounded call-stack theorem.
pub const FORMAL_COMPILER_V3_MAXIMUM_CALL_DEPTH: u8 = {spec["maximum_call_depth"]};
/// Minimum trip count modeled by the bounded loop theorem.
pub const FORMAL_COMPILER_V3_MINIMUM_LOOP_TRIP_COUNT: u8 = {spec["minimum_loop_trip_count"]};
/// Maximum trip count modeled by the bounded loop theorem.
pub const FORMAL_COMPILER_V3_MAXIMUM_LOOP_TRIP_COUNT: u8 = {spec["maximum_loop_trip_count"]};
/// Exact readonly access count in the composed kernel fragment.
pub const FORMAL_COMPILER_V3_READONLY_ACCESSES: u8 = {spec["readonly_accesses"]};
/// Exact disjoint write count in the composed kernel fragment.
pub const FORMAL_COMPILER_V3_DISJOINT_WRITES: u8 = {spec["disjoint_writes"]};
/// The formal byte codec is little endian.
pub const FORMAL_COMPILER_V3_USES_LITTLE_ENDIAN: bool = true;
/// The composed access theorem binds a runtime extent value.
pub const FORMAL_COMPILER_V3_USES_DYNAMIC_EXTENT: bool = true;
/// Closed scalar operation vocabulary shared with the generated formal model.
pub const FORMAL_COMPILER_V3_SCALAR_OPERATIONS: &[(&str, u8)] = &[
{operations}
];
'''


def render_verus(spec: dict[str, object]) -> str:
    operation_tags = "\n".join(
        "pub open spec fn formal_compiler_v3_"
        f'{item.replace("-", "_")}_tag() -> nat {{ {tag} }}'
        for tag, item in enumerate(spec["scalar_operations"], start=1)
    )
    operation_count = len(spec["scalar_operations"])
    return f'''// @generated by scripts/generate-formal-compiler-v3-spec.py; do not edit.
use vstd::prelude::*;

verus! {{

pub open spec fn formal_compiler_v3_schema_version() -> nat {{ {spec["schema_version"]} }}
pub open spec fn formal_compiler_v3_claim_version() -> nat {{ {spec["claim_version"]} }}
pub open spec fn formal_compiler_v3_word_bits() -> nat {{ {spec["word_bits"]} }}
pub open spec fn formal_compiler_v3_byte_width() -> nat {{ {spec["byte_width"]} }}
pub open spec fn formal_compiler_v3_helper_parameters() -> nat {{ {spec["helper_parameters"]} }}
pub open spec fn formal_compiler_v3_branch_arms() -> nat {{ {spec["branch_arms"]} }}
pub open spec fn formal_compiler_v3_maximum_call_depth() -> nat {{ {spec["maximum_call_depth"]} }}
pub open spec fn formal_compiler_v3_minimum_loop_trip_count() -> nat {{ {spec["minimum_loop_trip_count"]} }}
pub open spec fn formal_compiler_v3_maximum_loop_trip_count() -> nat {{ {spec["maximum_loop_trip_count"]} }}
pub open spec fn formal_compiler_v3_readonly_accesses() -> nat {{ {spec["readonly_accesses"]} }}
pub open spec fn formal_compiler_v3_disjoint_writes() -> nat {{ {spec["disjoint_writes"]} }}
pub open spec fn formal_compiler_v3_operation_count() -> nat {{ {operation_count} }}
pub open spec fn formal_compiler_v3_operation_is_closed(tag: nat) -> bool {{
    1 <= tag && tag <= formal_compiler_v3_operation_count()
}}
{operation_tags}

}}
'''


def update(path: Path, expected: str, check: bool) -> bool:
    actual = path.read_text(encoding="utf-8") if path.exists() else None
    if actual == expected:
        return True
    if check:
        print(f"generated V3 spec is stale: {path.relative_to(ROOT)}", file=sys.stderr)
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(expected, encoding="utf-8")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        spec = load_spec()
        valid = update(RUST, render_rust(spec), args.check)
        valid &= update(VERUS, render_verus(spec), args.check)
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(f"invalid Formal Compiler V3 spec: {error}", file=sys.stderr)
        return 1
    return 0 if valid else 1


if __name__ == "__main__":
    raise SystemExit(main())
