d /run/fe2o3 0755 root root -
d /var/lib/fe2o3 0755 root root -
d /var/lib/fe2o3/compiler-execution 0700 fe2o3-compiler fe2o3-compiler -
d /var/lib/fe2o3/external-anchor 0700 fe2o3-anchor fe2o3-anchor -
d /etc/fe2o3 0755 root root -
d /etc/fe2o3/compiler-execution 0755 root root -
