//! Private original-meter evaluator over the exact prepared root source.
//! No normal admission, standalone certificate, root recipe or attachment.
use super::assertion_resources_v1::AssertionResourcesV1;
use super::bf16_nominal_preparation_resources_v1::resource;
use super::bf16_nominal_source_preparation_v1::NominalRootCfgSourceV1;
use super::*;
use fe2o3_kernel_ir::CanonicalKernelIrVerificationResourceErrorV1 as Resource;
use std::ops::Deref;

pub(super) enum AssertionGraphV1<'a> {
    Owned(ProjectedLoopCfgV1),
    Borrowed(&'a ProjectedLoopCfgV1),
}
impl Deref for AssertionGraphV1<'_> {
    type Target = ProjectedLoopCfgV1;
    fn deref(&self) -> &Self::Target {
        match self {
            Self::Owned(value) => value,
            Self::Borrowed(value) => value,
        }
    }
}
pub(super) enum AssertionTableV1<'a, T> {
    Owned(Vec<T>),
    Borrowed(&'a [T]),
}
impl<T> Deref for AssertionTableV1<'_, T> {
    type Target = [T];
    fn deref(&self) -> &Self::Target {
        match self {
            Self::Owned(value) => value,
            Self::Borrowed(value) => value,
        }
    }
}
impl<T: Clone> Clone for AssertionTableV1<'_, T> {
    fn clone(&self) -> Self {
        // Existing out-of-core callers hold the Owned legacy arm and keep the
        // exact old Vec::clone. The strict evaluator never clones these tables.
        match self {
            Self::Owned(value) => Self::Owned(value.clone()),
            Self::Borrowed(value) => Self::Borrowed(value),
        }
    }
}

pub(super) struct PreparedAssertionDecisionsV1<'s> {
    function: &'s SemanticFunctionDeclV1,
    graph: &'s ProjectedLoopCfgV1,
    types: &'s [SemanticTypeDeclV1],
    decisions: Vec<bool>,
    logical_work: usize,
}
impl PreparedAssertionDecisionsV1<'_> {
    pub(super) fn function(&self) -> &SemanticFunctionDeclV1 {
        self.function
    }
    pub(super) fn graph(&self) -> &ProjectedLoopCfgV1 {
        self.graph
    }
    pub(super) fn types(&self) -> &[SemanticTypeDeclV1] {
        self.types
    }
    pub(super) fn decisions(&self) -> &[bool] {
        &self.decisions
    }
    pub(super) fn logical_work(&self) -> usize {
        self.logical_work
    }
}

pub(super) fn assertion_resource_overflow_v1() -> ProductionRankedProjectionErrorV1 {
    resource(Resource::Arithmetic)
}
pub(super) fn assertion_resource_accounting_v1() -> ProductionRankedProjectionErrorV1 {
    resource(Resource::Accounting)
}

/// Fixed conservative scalar/local envelope for one source-audited evaluator
/// frame. No value of this tuple is created. Heap referents are NOT included:
/// every vector capacity and model payload is separately paid at its operation.
/// The complete return/error representation is added by reserve_frame<T>.
pub(super) fn assertion_evaluator_local_frame_v1()
-> Result<usize, ProductionRankedProjectionErrorV1> {
    Ok(std::mem::size_of::<(
        [usize; 64],
        [u128; 16],
        [SemanticOperandV1; 16],
        [SemanticPlaceV1; 4],
        [SemanticCheckedBinaryRvalueV1; 4],
        [ScalarAssignmentSiteV1; 16],
        [std::slice::Iter<'static, fe2o3_mir_model::semantic_mir_v1::SemanticBasicBlockV1>; 4],
        [std::iter::Enumerate<
            std::slice::Iter<'static, fe2o3_mir_model::semantic_mir_v1::SemanticBasicBlockV1>,
        >; 4],
        [std::slice::Iter<'static, fe2o3_mir_model::semantic_mir_v1::SemanticStatementV1>; 2],
        [std::slice::Iter<'static, (SemanticOperandV1, ScalarAssignmentSiteV1)>; 4],
        [std::array::IntoIter<(&'static SemanticOperandV1, &'static SemanticOperandV1), 2>; 4],
        [std::ops::Range<usize>; 4],
        [std::iter::Rev<std::ops::Range<usize>>; 4],
        [Option<UnsignedRangeProofV1>; 16],
        [AssertionRangeOperandTaskV1; 4],
        [AssertionRangeExpressionTaskV1; 4],
        [AssertionRangeFrameV1<'static>; 4],
        [AuthenticatedCheckedBinaryValueV1; 4],
        [AuthenticatedScaledQuotientRemainderV1; 2],
        [AuthenticatedQuotientStrictBoundV1; 2],
        [Vec<usize>; 8],
        [AssertionQueueV1<'static>; 4],
        [AssertionSetV1<'static, usize>; 4],
        [AssertionSetV1<'static, (usize, usize)>; 4],
        [AssertionCacheV1<'static>; 2],
    )>())
}

/// Source-audited acyclic callgraph roster: one simultaneously live frame per
/// listed vertex. The six recursive vertices are omitted; every call to them
/// prepays a fresh complete frame BEFORE entering. New helpers are included.
/// No arbitrary callback, dynamic user equality/clone, or evaluator reentrancy
/// exists in this closed callgraph. This is a logical resource bound, not a
/// compiler-generated byte count for a target's optimized machine stack.
fn reserve_assertion_evaluator_frames_v1<'a>(
    resources: &mut AssertionResourcesV1<'a>,
) -> Result<(), ProductionRankedProjectionErrorV1> {
    let locals = assertion_evaluator_local_frame_v1()?;
    // checked_assertion_index_v1
    resources
        .reserve_frame::<Result<Vec<Vec<usize>>, ProductionRankedProjectionErrorV1>>(locals)?;
    // new_borrowed_assertion_tables_v1
    resources
        .reserve_frame::<Result<SemanticAssertProofsV1<'a>, ProductionRankedProjectionErrorV1>>(
            locals,
        )?;
    // analyze_existing_assertions_v1
    resources.reserve_frame::<Result<Vec<bool>, ProductionRankedProjectionErrorV1>>(locals)?;
    // proves_literal_shift_assert_v1
    resources.reserve_frame::<Result<bool, ProductionRankedProjectionErrorV1>>(locals)?;
    // proves_checked_overflow_assert_v1
    resources.reserve_frame::<Result<bool, ProductionRankedProjectionErrorV1>>(locals)?;
    // authenticated_checked_binary_value_v1
    resources.reserve_frame::<Result<Option<AuthenticatedCheckedBinaryValueV1>, ProductionRankedProjectionErrorV1>>(locals)?;
    // authenticated_checked_binary_local_value_v1
    resources.reserve_frame::<Result<Option<AuthenticatedCheckedBinaryValueV1>, ProductionRankedProjectionErrorV1>>(locals)?;
    // charge
    resources.reserve_frame::<Result<(), ProductionRankedProjectionErrorV1>>(locals)?;
    // scalar_unsigned_maximum
    resources.reserve_frame::<Option<u128>>(locals)?;
    // unsigned_integer_bits
    resources.reserve_frame::<Option<u16>>(locals)?;
    // literal_unsigned_subtraction_upper_range_v1
    resources.reserve_frame::<Option<UnsignedRangeProofV1>>(locals)?;
    // assertion_range_operand_task_v1
    resources
        .reserve_frame::<Result<AssertionRangeOperandTaskV1, ProductionRankedProjectionErrorV1>>(
            locals,
        )?;
    // assertion_range_expression_task_v1
    resources
        .reserve_frame::<Result<AssertionRangeExpressionTaskV1, ProductionRankedProjectionErrorV1>>(
            locals,
        )?;
    // push_assertion_reserved_vec_v1
    resources.reserve_frame::<Result<(), ProductionRankedProjectionErrorV1>>(locals)?;
    // push_assertion_range_frame_with_resources_v1
    resources.reserve_frame::<Result<(), ProductionRankedProjectionErrorV1>>(locals)?;
    // push_assertion_range_value_with_resources_v1
    resources.reserve_frame::<Result<(), ProductionRankedProjectionErrorV1>>(locals)?;
    // pop_assertion_range_value_with_resources_v1
    resources
        .reserve_frame::<Result<Option<UnsignedRangeProofV1>, ProductionRankedProjectionErrorV1>>(
            locals,
        )?;
    // schedule_assertion_range_operand_v1
    resources.reserve_frame::<Result<(), ProductionRankedProjectionErrorV1>>(locals)?;
    // schedule_assertion_range_expression_v1
    resources.reserve_frame::<Result<(), ProductionRankedProjectionErrorV1>>(locals)?;
    // schedule_assertion_local_narrowing_v1
    resources.reserve_frame::<Result<(), ProductionRankedProjectionErrorV1>>(locals)?;
    // range_of_binary
    resources
        .reserve_frame::<Result<Option<UnsignedRangeProofV1>, ProductionRankedProjectionErrorV1>>(
            locals,
        )?;
    // authenticated_checked_binary_source_v1
    resources.reserve_frame::<Result<Option<AuthenticatedCheckedBinaryValueV1>, ProductionRankedProjectionErrorV1>>(locals)?;
    // exact_binary_source_v1
    resources.reserve_frame::<Result<
        Option<(ScalarAssignmentSiteV1, SemanticOperandV1, SemanticOperandV1)>,
        ProductionRankedProjectionErrorV1,
    >>(locals)?;
    // authenticated_scaled_quotient_remainder_v1
    resources.reserve_frame::<Result<Option<AuthenticatedScaledQuotientRemainderV1>, ProductionRankedProjectionErrorV1>>(locals)?;
    // proves_scaled_quotient_remainder_nonnegative_v1
    resources.reserve_frame::<Result<bool, ProductionRankedProjectionErrorV1>>(locals)?;
    // proves_authenticated_unsigned_lower_bound_subtraction_v1
    resources.reserve_frame::<Result<bool, ProductionRankedProjectionErrorV1>>(locals)?;
    // same_edge_stable_unsigned_subtraction_value_v1
    resources.reserve_frame::<Result<bool, ProductionRankedProjectionErrorV1>>(locals)?;
    // comparison_edge_authenticates_each_dynamic_use_v1
    resources.reserve_frame::<Result<bool, ProductionRankedProjectionErrorV1>>(locals)?;
    // same_exact_unsigned_value_v1
    resources.reserve_frame::<Result<bool, ProductionRankedProjectionErrorV1>>(locals)?;
    // exact_unsigned_value_origin_v1
    resources.reserve_frame::<Result<
        Option<(SemanticOperandV1, ScalarAssignmentSiteV1)>,
        ProductionRankedProjectionErrorV1,
    >>(locals)?;
    // explicit_checked_product_maximum_v1
    resources.reserve_frame::<Result<Option<u128>, ProductionRankedProjectionErrorV1>>(locals)?;
    // same_checked_product_operand_v1
    resources.reserve_frame::<Result<bool, ProductionRankedProjectionErrorV1>>(locals)?;
    // local_is_stable_from_operand_use_site_v1
    resources.reserve_frame::<Result<bool, ProductionRankedProjectionErrorV1>>(locals)?;
    // proves_strictly_bounded_unsigned_product_v1
    resources.reserve_frame::<Result<bool, ProductionRankedProjectionErrorV1>>(locals)?;
    // proves_strictly_bounded_unsigned_flat_index_v1
    resources.reserve_frame::<Result<bool, ProductionRankedProjectionErrorV1>>(locals)?;
    // proves_strictly_bounded_unsigned_nested_flat_index_v1
    resources.reserve_frame::<Result<bool, ProductionRankedProjectionErrorV1>>(locals)?;
    // proves_nested_offset_sum_below_product_extent_v1
    resources.reserve_frame::<Result<bool, ProductionRankedProjectionErrorV1>>(locals)?;
    // authenticated_strict_unsigned_bounds_v1
    resources.reserve_frame::<Result<
        Vec<(SemanticOperandV1, ScalarAssignmentSiteV1)>,
        ProductionRankedProjectionErrorV1,
    >>(locals)?;
    // same_edge_stable_unsigned_value_v1
    resources.reserve_frame::<Result<bool, ProductionRankedProjectionErrorV1>>(locals)?;
    // local_is_stable_between_sites_v1
    resources.reserve_frame::<Result<bool, ProductionRankedProjectionErrorV1>>(locals)?;
    // block_terminator_defines_local_v1
    resources.reserve_frame::<bool>(locals)?;
    // exact_same_type_use_alias_origin_v1
    resources.reserve_frame::<Result<
        Option<(SemanticOperandV1, ScalarAssignmentSiteV1)>,
        ProductionRankedProjectionErrorV1,
    >>(locals)?;
    // unsigned_operand_stable_from_edge_to_use_v1
    resources.reserve_frame::<Result<bool, ProductionRankedProjectionErrorV1>>(locals)?;
    // local_stable_after_comparison_and_edge_to_use_v1
    resources.reserve_frame::<Result<bool, ProductionRankedProjectionErrorV1>>(locals)?;
    // local_is_stable_between_edge_and_site_v1
    resources.reserve_frame::<Result<bool, ProductionRankedProjectionErrorV1>>(locals)?;
    // block_defines_local_in_statement_range_v1
    resources.reserve_frame::<Result<bool, ProductionRankedProjectionErrorV1>>(locals)?;
    // exact_checked_overflow_flag_source_local_v1
    resources.reserve_frame::<Result<Option<usize>, ProductionRankedProjectionErrorV1>>(locals)?;
    // operand_has_globally_stable_value_at_v1
    resources.reserve_frame::<Result<bool, ProductionRankedProjectionErrorV1>>(locals)?;
    // assignment_dominates_use
    resources.reserve_frame::<Result<bool, ProductionRankedProjectionErrorV1>>(locals)?;
    // exact_reaching_assignment_v1
    resources
        .reserve_frame::<Result<Option<ScalarAssignmentSiteV1>, ProductionRankedProjectionErrorV1>>(
            locals,
        )?;
    // zero_excluding_edge_dominates
    resources.reserve_frame::<Result<bool, ProductionRankedProjectionErrorV1>>(locals)?;
    // blocks_reaching
    resources.reserve_frame::<Result<Vec<bool>, ProductionRankedProjectionErrorV1>>(locals)?;
    // local_is_stable_between_edge_and_use
    resources.reserve_frame::<Result<bool, ProductionRankedProjectionErrorV1>>(locals)?;
    // local_is_stable_from_revalidating_edge_to_use
    resources.reserve_frame::<Result<bool, ProductionRankedProjectionErrorV1>>(locals)?;
    // comparison_zero_excluding_target
    resources.reserve_frame::<Result<Option<usize>, ProductionRankedProjectionErrorV1>>(locals)?;
    // operand_is_exact_unsigned_zero
    resources.reserve_frame::<bool>(locals)?;
    // local_has_globally_stable_value_at
    resources.reserve_frame::<Result<bool, ProductionRankedProjectionErrorV1>>(locals)?;
    // block_defines_local
    resources.reserve_frame::<Result<bool, ProductionRankedProjectionErrorV1>>(locals)?;
    // local_is_value_preserving_alias_of
    resources.reserve_frame::<Result<bool, ProductionRankedProjectionErrorV1>>(locals)?;
    // block_dominates
    resources.reserve_frame::<Result<bool, ProductionRankedProjectionErrorV1>>(locals)?;
    // edge_set_dominates
    resources.reserve_frame::<Result<bool, ProductionRankedProjectionErrorV1>>(locals)?;
    Ok(())
}

struct BorrowedAssertionComponentsV1<'s> {
    types: &'s [SemanticTypeDeclV1],
    function: &'s SemanticFunctionDeclV1,
    graph: &'s ProjectedLoopCfgV1,
    counts: &'s [u8],
    blocks: &'s [Vec<usize>],
    escaped: &'s [bool],
    assignments: &'s [Option<ScalarAssignmentSiteV1>],
}

/// No source authority is created by this common private evaluator core.
fn analyze_borrowed_assertion_components_v1(
    components: BorrowedAssertionComponentsV1<'_>,
    resources: &mut PreparationResourcesV1<'_, '_>,
) -> Result<(Vec<bool>, usize), ProductionRankedProjectionErrorV1> {
    let mut resources = AssertionResourcesV1::strict(resources)?;
    // Pay this entry's complete constructor/locals/output/error transfer before
    // moving the handle into the actual evaluator. C's envelope is additional.
    resources.reserve_frame::<(Vec<bool>, usize)>(
        std::mem::size_of::<BorrowedAssertionComponentsV1<'static>>()
            .checked_add(assertion_evaluator_local_frame_v1()?)
            .ok_or_else(assertion_resource_overflow_v1)?,
    )?;
    reserve_assertion_evaluator_frames_v1(&mut resources)?;
    let mut proof = SemanticAssertProofsV1::new_borrowed_assertion_tables_v1(
        components.types,
        components.function,
        components.graph,
        components.counts,
        components.blocks,
        components.escaped,
        components.assignments,
        resources,
    )?;
    let decisions = proof.analyze_existing_assertions_v1()?;
    proof.resources.extra_work(64)?;
    if proof.resources.is_denied() || decisions.len() != components.function.blocks().len() {
        return Err(assertion_resource_accounting_v1());
    }
    let logical_work = proof.work;
    // Evaluator/caches and ORIGINAL exclusive adapter borrow end before return.
    // The enclosing owner keeps ALL accepted credits until the mask is dropped.
    drop(proof);
    Ok((decisions, logical_work))
}

pub(super) fn analyze_prepared_root_assertions_with_resources_v1<'s>(
    view: &'s NominalRootCfgSourceV1<'_>,
    resources: &mut PreparationResourcesV1<'_, '_>,
) -> Result<PreparedAssertionDecisionsV1<'s>, ProductionRankedProjectionErrorV1> {
    // The exact entry/transfer is paid on ORIGINAL before source/table assembly.
    // The short handle must end before the common core exclusively borrows it.
    {
        let mut entry = AssertionResourcesV1::strict(resources)?;
        entry.reserve_frame::<PreparedAssertionDecisionsV1<'s>>(std::mem::size_of::<
            BorrowedAssertionComponentsV1<'s>,
        >())?;
        entry.extra_work(64)?;
    }
    let function: &'s SemanticFunctionDeclV1 = view.function();
    let graph: &'s ProjectedLoopCfgV1 = view.graph();
    let types: &'s [SemanticTypeDeclV1] = view.types();
    let rich = view.source_tables().rich();
    if !std::ptr::eq(function, rich.function()) {
        return Err(ProductionRankedProjectionErrorV1::Unsupported(
            "prepared assertion function differs from exact rich source",
        ));
    }
    let (decisions, logical_work) = analyze_borrowed_assertion_components_v1(
        BorrowedAssertionComponentsV1 {
            types,
            function,
            graph,
            counts: rich.scalar_counts(),
            blocks: rich.scalar_blocks(),
            escaped: rich.address_escaped(),
            assignments: rich.scalar_assignments(),
        },
        resources,
    )?;
    Ok(PreparedAssertionDecisionsV1 {
        function,
        graph,
        types,
        decisions,
        logical_work,
    })
}

/// Raw semantic fixtures only. Never reachable from admitted-owner production
/// construction, never fabricates a prepared owner or an assertion certificate.
#[cfg(test)]
pub(super) fn analyze_assertion_components_for_test_v1(
    types: &[SemanticTypeDeclV1],
    function: &SemanticFunctionDeclV1,
    graph: &ProjectedLoopCfgV1,
    inventory: &AssertionDefinitionInventoryV1,
    resources: &mut PreparationResourcesV1<'_, '_>,
) -> Result<(Vec<bool>, usize), ProductionRankedProjectionErrorV1> {
    {
        let mut entry = AssertionResourcesV1::strict(resources)?;
        entry.reserve_frame::<(Vec<bool>, usize)>(std::mem::size_of::<
            BorrowedAssertionComponentsV1<'static>,
        >())?;
        entry.extra_work(64)?;
    }
    analyze_borrowed_assertion_components_v1(
        BorrowedAssertionComponentsV1 {
            types,
            function,
            graph,
            counts: &inventory.counts,
            blocks: &inventory.blocks,
            escaped: &inventory.address_escaped,
            assignments: &inventory.assignments,
        },
        resources,
    )
}

/// Closed synthetic probes exercise real non-top-level evaluator paths. These
/// variants exist only in test builds; there is no external callback/reentry.
#[cfg(test)]
pub(super) enum AssertionFixedProbeV1<'a> {
    Quotient {
        numerator: &'a SemanticOperandV1,
        divisor: &'a SemanticOperandV1,
        use_site: ScalarAssignmentSiteV1,
    },
    FlatPath {
        operand: &'a SemanticOperandV1,
        operand_use: ScalarAssignmentSiteV1,
        sum_site: ScalarAssignmentSiteV1,
        scalar_type: SemanticTypeIdV1,
        offsets: &'a [(SemanticOperandV1, ScalarAssignmentSiteV1)],
        remaining: usize,
    },
    Nested {
        checked: &'a SemanticCheckedBinaryRvalueV1,
        sum_site: ScalarAssignmentSiteV1,
    },
    PanicAfterRealMask,
}
#[cfg(test)]
pub(super) enum AssertionFixedProbeResultV1 {
    Quotient(Option<AuthenticatedQuotientStrictBoundV1>),
    Flat(bool),
}

/// Test owner must retain every accepted credit until this result (or unwind
/// payload) and all evaluator locals are dropped. No credit transfer/refund here.
#[cfg(test)]
pub(super) fn analyze_assertion_fixed_probe_for_test_v1(
    types: &[SemanticTypeDeclV1],
    function: &SemanticFunctionDeclV1,
    graph: &ProjectedLoopCfgV1,
    inventory: &AssertionDefinitionInventoryV1,
    probe: AssertionFixedProbeV1<'_>,
    resources: &mut PreparationResourcesV1<'_, '_>,
) -> Result<(AssertionFixedProbeResultV1, usize), ProductionRankedProjectionErrorV1> {
    let mut resources = AssertionResourcesV1::strict(resources)?;
    resources.reserve_frame::<(AssertionFixedProbeResultV1, usize)>(
        std::mem::size_of::<AssertionFixedProbeV1<'static>>()
            .checked_add(assertion_evaluator_local_frame_v1()?)
            .ok_or_else(assertion_resource_overflow_v1)?,
    )?;
    reserve_assertion_evaluator_frames_v1(&mut resources)?;
    let mut proof = SemanticAssertProofsV1::new_borrowed_assertion_tables_v1(
        types,
        function,
        graph,
        &inventory.counts,
        &inventory.blocks,
        &inventory.address_escaped,
        &inventory.assignments,
        resources,
    )?;
    let result = match probe {
        AssertionFixedProbeV1::Quotient {
            numerator,
            divisor,
            use_site,
        } => {
            proof
                .resources
                .reserve_frame::<Option<AuthenticatedQuotientStrictBoundV1>>(
                    assertion_evaluator_local_frame_v1()?,
                )?;
            AssertionFixedProbeResultV1::Quotient(
                proof.quotient_strict_product_upper_bound_v1(numerator, divisor, use_site)?,
            )
        }
        AssertionFixedProbeV1::FlatPath {
            operand,
            operand_use,
            sum_site,
            scalar_type,
            offsets,
            remaining,
        } => {
            let capacity = offsets
                .len()
                .checked_add(remaining)
                .ok_or_else(assertion_resource_overflow_v1)?;
            let mut copied_offsets = Vec::new();
            proof.resources.reserve_vec(
                &mut copied_offsets,
                capacity,
                LegacyReserve::Exact,
                "test flat-index offset storage cannot be reserved",
            )?;
            proof.resources.extra_work(offsets.len())?;
            for (operand, site) in offsets {
                let copied = proof.resources.clone_operand(operand)?;
                let value = (copied, *site);
                SemanticAssertProofsV1::push_assertion_reserved_vec_v1(
                    &mut proof.resources,
                    &mut copied_offsets,
                    value,
                )?;
            }
            proof
                .resources
                .reserve_frame::<bool>(assertion_evaluator_local_frame_v1()?)?;
            AssertionFixedProbeResultV1::Flat(
                proof.proves_strictly_bounded_unsigned_flat_index_path_v1(
                    operand,
                    operand_use,
                    sum_site,
                    scalar_type,
                    &mut copied_offsets,
                    remaining,
                )?,
            )
        }
        AssertionFixedProbeV1::Nested { checked, sum_site } => AssertionFixedProbeResultV1::Flat(
            proof.proves_strictly_bounded_unsigned_nested_flat_index_v1(checked, sum_site)?,
        ),
        AssertionFixedProbeV1::PanicAfterRealMask => {
            let _actual_mask = proof.analyze_existing_assertions_v1()?;
            // Static test panic only: no arbitrary callback into a live analyzer.
            proof.resources.reserve_frame::<&'static str>(0)?;
            proof.resources.extra_work(64)?;
            panic!("synthetic assertion evaluator unwind after real mask");
        }
    };
    proof.resources.extra_work(64)?;
    if proof.resources.is_denied() {
        return Err(assertion_resource_accounting_v1());
    }
    let logical_work = proof.work;
    drop(proof);
    Ok((result, logical_work))
}
