//! Additive typed seed-only envelope, retained until the entire owner drops.
use super::*;
type Facts = CanonicalSourceAssertionFactsV1<'static, 'static, 'static, 'static, 'static>;
pub(super) fn bytes() -> BResult<usize> {
    const ROWS: usize = 12;
    let rows = [
        size_of::<(
            RetainedInvocationSeedV1,
            SeedPhase,
            SeedKey,
            Option<SeedKey>,
            WriterFloor,
            WriterFloor,
            Option<WriterFloor>,
            Option<(usize, usize, usize, usize)>,
            Vec<usize>,
            Vec<usize>,
            usize,
            usize,
        )>(),
        size_of::<(
            &mut RetainedInvocationSeedV1,
            &Source<'static>,
            Source<'static>,
            &[u8],
            &[bool],
            &SemanticOptionDominanceV1,
            &SemanticEnumPayloadDominanceV1,
            Option<u64>,
            &RetainedInitialCapabilityGraphV1,
            &mut InitialDestinations,
            &RetainedBeforeArgumentWritersV1,
            &mut RootEntryPrefixV1,
            &mut Prep<'static, 'static>,
            BResult<()>,
        )>(),
        size_of::<(
            SourceIdentity,
            GraphSourceKey,
            GraphSourceKey,
            SeedKey,
            SeedKey,
            Snapshot,
            Snapshot,
            Option<Snapshot>,
            Option<Backend>,
            Backend,
            &Backend,
            Resource,
            bool,
            usize,
            usize,
            usize,
            Option<usize>,
            BResult<()>,
            BResult<usize>,
        )>(),
        size_of::<(
            &RetainedInvocationSeedV1,
            &Source<'static>,
            &[u8],
            &[bool],
            &RetainedInitialCapabilityGraphV1,
            &InitialDestinations,
            &RetainedBeforeArgumentWritersV1,
            &RootEntryPrefixV1,
            &mut Prep<'static, 'static>,
            WriterFloor,
            WriterFloor,
            usize,
            usize,
            BResult<()>,
            BResult<usize>,
            BResult<u32>,
        )>(),
        size_of::<(
            std::slice::Iter<'static, Option<ProjectedDisjointIndexV1>>,
            std::slice::Iter<'static, Option<ProjectedGridLeaderV1>>,
            std::slice::Iter<'static, Option<GuardPredicateV1>>,
            &Option<ProjectedDisjointIndexV1>,
            &Option<ProjectedGridLeaderV1>,
            &Option<GuardPredicateV1>,
            usize,
            usize,
            bool,
        )>(),
        // Slice equality and counted row scans use no captured heap payload.
        size_of::<(
            &[u8],
            &[u8],
            std::slice::Iter<'static, u8>,
            std::slice::Iter<'static, u8>,
            &u8,
            &u8,
            bool,
            std::iter::Enumerate<std::iter::Copied<std::slice::Iter<'static, usize>>>,
            usize,
            usize,
            ProductionRankedValueIdV1,
            Option<u32>,
            Option<&u8>,
            Option<u8>,
            Option<&bool>,
            Option<bool>,
            Option<&Option<ProjectedDisjointIndexV1>>,
            Option<ProjectedDisjointIndexV1>,
            ProjectedDisjointIndexV1,
            ProductionRankedOperationV1,
            Option<&ProductionRankedOperationV1>,
        )>(),
        size_of::<(
            &mut PendingWholeRootBeforeArgumentWritersV1<'static>,
            &PendingWholeRootBeforeArgumentWritersV1<'static>,
            &ProductionPreRankedKirOwnerV1,
            SemanticFunctionIdV1,
            &mut Facts,
            &mut usize,
            bool,
            BResult<()>,
            Result<()>,
            QueryError,
            Source<'static>,
            Snapshot,
            Option<Snapshot>,
        )>(),
        size_of::<(
            &mut PendingBeforeProvenanceV1,
            &PendingBeforeProvenanceV1,
            &mut PendingBeforeScalarV1,
            &PendingBeforeScalarV1,
            &AssertionDefinitionInventoryV1,
            &SemanticOptionDominanceV1,
            &SemanticEnumPayloadDominanceV1,
            &mut InitialDestinations,
            &InitialDestinations,
            BeforeCapabilitiesV1<'static>,
            &RetainedInitialCapabilityGraphV1,
            &mut RetainedInvocationSeedV1,
        )>(),
        size_of::<(
            &ActualSelectedInputsV1<'static>,
            &ProductionRankedRootInputV1,
            &LaunchContract,
            Option<u64>,
            BlockSize,
            u32,
            u64,
            Option<u64>,
        )>(),
        donor::retained_invocation_seed_call_frame_v1()?,
        retained_custody_snapshot_frame_v1(),
        size_of::<(
            [usize; ROWS],
            std::array::IntoIter<usize, ROWS>,
            usize,
            usize,
            Option<usize>,
            BResult<usize>,
        )>(),
    ];
    rows.into_iter().try_fold(0usize, |sum, row| {
        sum.checked_add(row).ok_or_else(arithmetic)
    })
}
