//! Additive typed envelope for the private initial graph. No storage release.
use super::*;
use fe2o3_mir_model::semantic_mir_v1::{
    SemanticAggregateKindV1, SemanticAggregateRvalueV1, SemanticAssignmentV1, SemanticBasicBlockV1,
    SemanticCallDestinationV1, SemanticProjectionV1, SemanticRvalueV1, SemanticStatementV1,
};
type Facts = CanonicalSourceAssertionFactsV1<'static, 'static, 'static, 'static, 'static>;
pub(super) fn bytes() -> BResult<usize> {
    const ROWS: usize = 17;
    let rows = [
        // Component header, initial transfers and terminal/completion carriers.
        size_of::<(
            RetainedInitialCapabilityGraphV1,
            GraphPhase,
            GraphSourceKey,
            Option<GraphSourceKey>,
            WriterFloor,
            Option<WriterFloor>,
            Option<u64>,
            Vec<u8>,
            Option<(usize, usize, usize, usize)>,
        )>(),
        // Raw DATA inputs and retained destinations, never an owned graph return.
        size_of::<(
            &mut RetainedInitialCapabilityGraphV1,
            &Source<'static>,
            Source<'static>,
            &[u8],
            &SemanticOptionDominanceV1,
            &SemanticEnumPayloadDominanceV1,
            Option<u64>,
            &mut InitialDestinations,
            &mut RetainedBeforeArgumentWritersV1,
            &RootEntryPrefixV1,
            &mut Prep<'static, 'static>,
        )>(),
        // Fixed identity, writer floors, bounds and saved-error/custody checks.
        size_of::<(
            SourceIdentity,
            GraphSourceKey,
            GraphSourceKey,
            WriterFloor,
            WriterFloor,
            Snapshot,
            Snapshot,
            Option<Snapshot>,
            Option<Backend>,
            Backend,
            &Backend,
            Resource,
            bool,
            usize,
            usize,
            Option<usize>,
            BResult<()>,
            BResult<usize>,
        )>(),
        // Initial all-None checks and exact u8 copy into an attached destination.
        size_of::<(
            std::slice::Iter<'static, Option<ProjectedDisjointIndexV1>>,
            std::slice::Iter<'static, Option<ProjectedGridLeaderV1>>,
            std::slice::Iter<'static, Option<GuardPredicateV1>>,
            std::slice::Iter<'static, Vec<CapabilityEdgeV1>>,
            &[u8],
            &mut Vec<u8>,
            &Option<ProjectedDisjointIndexV1>,
            &Option<ProjectedGridLeaderV1>,
            &Option<GuardPredicateV1>,
            &Vec<CapabilityEdgeV1>,
        )>(),
        // Exact donor outer/statement scan and pattern bindings.
        size_of::<(
            std::iter::Enumerate<std::slice::Iter<'static, SemanticBasicBlockV1>>,
            std::iter::Enumerate<std::slice::Iter<'static, SemanticStatementV1>>,
            usize,
            &SemanticBasicBlockV1,
            usize,
            &SemanticStatementV1,
            &SemanticAssignmentV1,
            &SemanticRvalueKindV1,
            &SemanticPlaceV1,
            &SemanticRvalueV1,
            &SemanticAggregateRvalueV1,
            &SemanticAggregateKindV1,
            &[SemanticOperandV1],
            &u32,
        )>(),
        // Place/operand accounting and the visitor callback carrier.
        size_of::<(
            &SemanticOperandV1,
            Option<&SemanticPlaceV1>,
            &SemanticPlaceV1,
            std::slice::Iter<'static, SemanticOperandV1>,
            &[SemanticProjectionV1],
            &SemanticProjectionV1,
            std::slice::Iter<'static, SemanticProjectionV1>,
            &mut dyn FnMut(&SemanticOperandV1) -> BResult<()>,
            usize,
            usize,
            Option<usize>,
            BResult<()>,
        )>(),
        // Borrow/alias edge construction and per-row reserve/push transfers.
        size_of::<(
            usize,
            usize,
            bool,
            Option<&SemanticPlaceV1>,
            CapabilityEdgeV1,
            CapabilityEdgeKindV1,
            &mut [Vec<CapabilityEdgeV1>],
            &mut Vec<CapabilityEdgeV1>,
            &mut usize,
            &mut Vec<(usize, usize)>,
            (usize, usize),
            &mut Prep<'static, 'static>,
        )>(),
        // Enum store/load construction; all rows are Copy and stay in attached Vecs.
        size_of::<(
            PendingEnumPayloadStoreV1,
            PendingEnumPayloadLoadV1,
            &mut Vec<PendingEnumPayloadStoreV1>,
            &mut Vec<PendingEnumPayloadLoadV1>,
            Option<(usize, u32)>,
            &SemanticOperandV1,
            usize,
            usize,
            u32,
        )>(),
        // Current direct-call classification and Option/geometry bindings.
        size_of::<(
            &SemanticDirectCallV1,
            Option<&SemanticCallableDeclV1>,
            &SemanticCompilerIntrinsicOperationV1,
            SemanticLocalIdV1,
            Option<SemanticLocalIdV1>,
            SemanticDisjointIndexSpaceV1,
            SemanticOptionAvailabilityV1,
            Option<SemanticOptionAvailabilityV1>,
            Option<u64>,
            u64,
            u64,
            u64,
            u64,
            BResult<SemanticLocalIdV1>,
            Option<&SemanticCallDestinationV1>,
            &SemanticCallDestinationV1,
            Option<&SemanticOperandV1>,
            &SemanticOperandV1,
            &u64,
            &u64,
        )>(),
        // Metered store insertion sort and enum-load partition/dominance joins.
        size_of::<(
            std::ops::Range<usize>,
            usize,
            usize,
            PendingEnumPayloadStoreV1,
            PendingEnumPayloadStoreV1,
            std::iter::Copied<std::slice::Iter<'static, PendingEnumPayloadLoadV1>>,
            PendingEnumPayloadLoadV1,
            (usize, u32),
            usize,
            usize,
            &[PendingEnumPayloadStoreV1],
            Option<&PendingEnumPayloadStoreV1>,
            CapabilityEdgeKindV1,
            CapabilityEdgeV1,
            SemanticLocalIdV1,
            SemanticEnumPayloadAvailabilityV1,
            Option<SemanticEnumPayloadAvailabilityV1>,
            Option<u8>,
            &(usize, u32),
            usize,
            usize,
            bool,
        )>(),
        // Reserve arithmetic and allocation error carriers; no uncharged payload return.
        size_of::<(
            &mut Prep<'static, 'static>,
            usize,
            usize,
            Option<usize>,
            std::collections::TryReserveError,
            std::result::Result<(), std::collections::TryReserveError>,
            BResult<()>,
        )>(),
        // Sealed whole bridge and predecessor completion borrow.
        size_of::<(
            &mut PendingWholeRootBeforeArgumentWritersV1<'static>,
            &PendingWholeRootBeforeArgumentWritersV1<'static>,
            &ProductionPreRankedKirOwnerV1,
            SemanticFunctionIdV1,
            &mut Facts,
            &mut usize,
            bool,
            BResult<()>,
            Result<()>,
            QueryError,
        )>(),
        // Lexical split of existing Option/enum/scalar owners; no moves/clones.
        size_of::<(
            &mut PendingBeforeProvenanceV1,
            &PendingBeforeProvenanceV1,
            &mut PendingBeforeScalarV1,
            &PendingBeforeScalarV1,
            &AssertionDefinitionInventoryV1,
            &SemanticOptionDominanceV1,
            &SemanticEnumPayloadDominanceV1,
            &mut InitialDestinations,
            &InitialDestinations,
            BeforeCapabilitiesV1<'static>,
        )>(),
        // Actual selected launch loan is read-only and already source-bound.
        size_of::<(
            &ActualSelectedInputsV1<'static>,
            &ProductionRankedRootInputV1,
            &LaunchContract,
            Option<u64>,
            BlockSize,
            u32,
            u64,
            Option<u64>,
        )>(),
        // Completion invokes existing snapshot/source-loan routines whose own
        // established frames remain charged; include these additional receivers.
        size_of::<(
            &RetainedInitialCapabilityGraphV1,
            &Source<'static>,
            &[u8],
            &InitialDestinations,
            &RetainedBeforeArgumentWritersV1,
            &RootEntryPrefixV1,
            &Prep<'static, 'static>,
            BResult<()>,
        )>(),
        retained_custody_snapshot_frame_v1(),
        size_of::<(
            [usize; ROWS],
            std::array::IntoIter<usize, ROWS>,
            usize,
            usize,
            Option<usize>,
            BResult<usize>,
        )>(),
    ];
    rows.into_iter().try_fold(0usize, |sum, row| {
        sum.checked_add(row).ok_or_else(arithmetic)
    })
}
