//! Additive logical frame policy for the independent retained donor.
//! This is not a native allocator or hash-table probe model.
use super::*;
use fe2o3_mir_model::semantic_mir_v1::{SemanticBasicBlockV1, SemanticLocalDeclV1};

pub(super) fn bytes() -> BResult<usize> {
    const ROWS: usize = 12;
    let rows = [
        size_of::<(
            RetainedOriginalReadsV1,
            OriginalPhase,
            ReadSourceKey,
            Option<ReadSourceKey>,
            Snapshot,
            Option<Snapshot>,
            Backend,
            Option<Backend>,
        )>(),
        size_of::<(
            &mut RetainedOriginalReadsV1,
            &[SemanticTypeDeclV1],
            &SemanticFunctionDeclV1,
            &[Option<ProjectedReadViewAccessV1>],
            &[Option<u32>],
            Option<&ProductionRankedOperationV1>,
            &mut Prep<'static, 'static>,
        )>(),
        size_of::<(
            std::iter::Zip<
                std::slice::Iter<'static, SemanticBasicBlockV1>,
                std::iter::Copied<std::slice::Iter<'static, Option<ProjectedReadViewAccessV1>>>,
            >,
            &SemanticBasicBlockV1,
            Option<ProjectedReadViewAccessV1>,
            ProjectedReadViewAccessV1,
            ProjectedReadViewV1,
            AllocationContractV1,
        )>(),
        size_of::<(
            &HashMap<u64, OriginalView>,
            &mut HashMap<u64, OriginalView>,
            Option<&OriginalView>,
            &ProjectedReadViewV1,
            &ProjectedViewV1,
            OriginalView,
            Option<OriginalView>,
            &mut OriginalView,
        )>(),
        size_of::<(
            ProjectedViewV1,
            ProductionRankedOperationV1,
            ProductionRankedValueIdV1,
            ProductionRankedValueV1,
            ProductionRankedValueV1,
            u32,
            u64,
            usize,
            &mut Vec<u64>,
            &mut Vec<ProductionRankedValueV1>,
        )>(),
        size_of::<(
            GuardedRankedAccessV1,
            Option<GuardedRankedAccessV1>,
            &mut GuardedRankedAccessV1,
            SemanticSourceProvenanceV1,
            AccessKindAttr,
            MemorySpaceAttr,
            (ProductionRankedValueV1, ProductionRankedValueV1),
            &mut Vec<(ProductionRankedValueV1, ProductionRankedValueV1)>,
        )>(),
        size_of::<(
            std::iter::Copied<std::slice::Iter<'static, u64>>,
            std::iter::Copied<std::slice::Iter<'static, ProductionRankedValueV1>>,
            std::slice::Iter<'static, SemanticLocalDeclV1>,
            &mut Vec<Option<u32>>,
            &mut Vec<Option<GuardedRankedAccessV1>>,
            &mut Vec<ProductionRankedOperationV1>,
        )>(),
        size_of::<(
            ProjectedReadValueV1,
            SemanticLocalIdV1,
            SemanticTypeIdV1,
            usize,
            usize,
            Option<u32>,
            &mut Option<u32>,
            u32,
            Option<usize>,
            u64,
            std::num::TryFromIntError,
        )>(),
        size_of::<(
            usize,
            usize,
            usize,
            usize,
            usize,
            Option<usize>,
            std::collections::TryReserveError,
            std::result::Result<(), std::collections::TryReserveError>,
            BResult<()>,
        )>(),
        size_of::<(
            Snapshot,
            Snapshot,
            Option<Snapshot>,
            bool,
            bool,
            Resource,
            Backend,
            &Backend,
            BResult<()>,
            BResult<usize>,
            BResult<u32>,
            BResult<ProductionRankedValueV1>,
            BResult<ProductionRankedValueIdV1>,
        )>(),
        retained_custody_snapshot_frame_v1(),
        size_of::<(
            [usize; ROWS],
            std::array::IntoIter<usize, ROWS>,
            usize,
            usize,
            Option<usize>,
            BResult<usize>,
        )>(),
    ];
    rows.into_iter().try_fold(0usize, |total, row| {
        total.checked_add(row).ok_or_else(arithmetic)
    })
}
