use super::*;

#[test]
fn authored_instruction_terminal_inverse_preserves_exact_identity() {
    use crate::trusted_device_items::TrustedAmdGpuInlineOperation as I;
    for item in [
        TrustedDeviceItem::AmdGpuInline(I::VMovB32),
        TrustedDeviceItem::AmdGpuInline(I::VAddU32),
        TrustedDeviceItem::AmdGpuInline(I::VSubU32),
        TrustedDeviceItem::AmdGpuInline(I::VAndB32),
        TrustedDeviceItem::AmdGpuInline(I::VOrB32),
        TrustedDeviceItem::AmdGpuInline(I::VXorB32),
        TrustedDeviceItem::AmdGpuOrderedXorAddE32,
        TrustedDeviceItem::AmdGpuOrderedProgramE32,
    ] {
        let rule = ProductionSemanticTerminalRuleV1::from_trusted_device_item(item);
        assert!(matches!(rule, ProductionSemanticTerminalRuleV1::Expand(_)));
        assert_eq!(rule.trusted_device_item(), item);
    }
}

#[test]
fn fill_terminals_have_explicit_workload_neutral_expansions() {
    let cases = [
        (
            TrustedDeviceItem::KernelContextIssue,
            ProductionTerminalExpansionV1::ContextIssue,
        ),
        (
            TrustedDeviceItem::ExecutionWorkgroupCurrent,
            ProductionTerminalExpansionV1::WorkgroupDerive,
        ),
        (
            TrustedDeviceItem::MaskedTile1DLoadMasked,
            ProductionTerminalExpansionV1::MaskedTileLoadU32,
        ),
        (
            TrustedDeviceItem::MaskedTile1DIntoFragment,
            ProductionTerminalExpansionV1::MaskedTileIntoFragmentU32,
        ),
        (
            TrustedDeviceItem::LaneFragment1DIntoParts,
            ProductionTerminalExpansionV1::LaneFragmentIntoPartsU32,
        ),
        (
            TrustedDeviceItem::ThreadIndexX,
            ProductionTerminalExpansionV1::ThreadIndex(SemanticAxisV1::X),
        ),
        (
            TrustedDeviceItem::ThreadIndexY,
            ProductionTerminalExpansionV1::ThreadIndex(SemanticAxisV1::Y),
        ),
        (
            TrustedDeviceItem::ThreadIndexZ,
            ProductionTerminalExpansionV1::ThreadIndex(SemanticAxisV1::Z),
        ),
        (
            TrustedDeviceItem::WorkgroupIndexX,
            ProductionTerminalExpansionV1::WorkgroupIndex(SemanticAxisV1::X),
        ),
        (
            TrustedDeviceItem::WorkgroupIndexY,
            ProductionTerminalExpansionV1::WorkgroupIndex(SemanticAxisV1::Y),
        ),
        (
            TrustedDeviceItem::WorkgroupIndexZ,
            ProductionTerminalExpansionV1::WorkgroupIndex(SemanticAxisV1::Z),
        ),
        (
            TrustedDeviceItem::WorkgroupDimensionX,
            ProductionTerminalExpansionV1::WorkgroupDimension(SemanticAxisV1::X),
        ),
        (
            TrustedDeviceItem::WorkgroupDimensionY,
            ProductionTerminalExpansionV1::WorkgroupDimension(SemanticAxisV1::Y),
        ),
        (
            TrustedDeviceItem::WorkgroupDimensionZ,
            ProductionTerminalExpansionV1::WorkgroupDimension(SemanticAxisV1::Z),
        ),
        (
            TrustedDeviceItem::GridDimensionX,
            ProductionTerminalExpansionV1::GridDimension(SemanticAxisV1::X),
        ),
        (
            TrustedDeviceItem::GridDimensionY,
            ProductionTerminalExpansionV1::GridDimension(SemanticAxisV1::Y),
        ),
        (
            TrustedDeviceItem::GridDimensionZ,
            ProductionTerminalExpansionV1::GridDimension(SemanticAxisV1::Z),
        ),
        (
            TrustedDeviceItem::ThreadIndex1d,
            ProductionTerminalExpansionV1::ThreadIndex1d,
        ),
        (
            TrustedDeviceItem::ThreadIndexGet,
            ProductionTerminalExpansionV1::ThreadIndexGet,
        ),
        (
            TrustedDeviceItem::ThreadIndexIntoDisjoint,
            ProductionTerminalExpansionV1::ThreadIndexIntoDisjoint,
        ),
        (
            TrustedDeviceItem::ThreadIndexCheckedShift,
            ProductionTerminalExpansionV1::ThreadIndexCheckedShift,
        ),
        (
            TrustedDeviceItem::DisjointIndexGet,
            ProductionTerminalExpansionV1::DisjointIndexGet,
        ),
        (
            TrustedDeviceItem::DisjointBlockComponentIndex,
            ProductionTerminalExpansionV1::DisjointBlockComponentIndex,
        ),
        (
            TrustedDeviceItem::DisjointIndexCheckedShift,
            ProductionTerminalExpansionV1::DisjointIndexCheckedShift,
        ),
        (
            TrustedDeviceItem::DisjointSliceLen,
            ProductionTerminalExpansionV1::DisjointSliceLen,
        ),
        (
            TrustedDeviceItem::DisjointSliceGetMut,
            ProductionTerminalExpansionV1::DisjointSliceGetMut,
        ),
        (
            TrustedDeviceItem::DisjointSliceGetDisjointMut,
            ProductionTerminalExpansionV1::DisjointSliceGetDisjointMut,
        ),
        (
            TrustedDeviceItem::GridLeaderCurrent,
            ProductionTerminalExpansionV1::GridLeaderCurrent,
        ),
        (
            TrustedDeviceItem::DisjointSliceGetMutExclusive,
            ProductionTerminalExpansionV1::DisjointSliceGetMutExclusive,
        ),
        (
            TrustedDeviceItem::WorkgroupSyncthreads,
            ProductionTerminalExpansionV1::WorkgroupBarrier,
        ),
        (
            TrustedDeviceItem::DeviceMath(DeviceMathDiagnosticItem::ContextFromCompiler),
            ProductionTerminalExpansionV1::MathContextCurrent,
        ),
        (
            TrustedDeviceItem::DeviceMath(DeviceMathDiagnosticItem::F32(F32MathFunction::Exp)),
            ProductionTerminalExpansionV1::MathF32(F32MathFunction::Exp),
        ),
        (
            TrustedDeviceItem::HalfOperation(TrustedHalfOperation::FromBits(
                NarrowFloatFormat::Bf16,
            )),
            ProductionTerminalExpansionV1::Bf16Conversion(ProductionBf16ConversionV1::FromBits),
        ),
        (
            TrustedDeviceItem::HalfOperation(TrustedHalfOperation::ToBits(NarrowFloatFormat::Bf16)),
            ProductionTerminalExpansionV1::Bf16Conversion(ProductionBf16ConversionV1::ToBits),
        ),
        (
            TrustedDeviceItem::HalfOperation(TrustedHalfOperation::FromF32(
                NarrowFloatFormat::Bf16,
            )),
            ProductionTerminalExpansionV1::Bf16Conversion(
                ProductionBf16ConversionV1::FromF32RoundTiesEven,
            ),
        ),
        (
            TrustedDeviceItem::HalfOperation(TrustedHalfOperation::ToF32(NarrowFloatFormat::Bf16)),
            ProductionTerminalExpansionV1::Bf16Conversion(ProductionBf16ConversionV1::ToF32),
        ),
        (
            TrustedDeviceItem::Gfx942CollectivesCurrent,
            ProductionTerminalExpansionV1::CollectiveContextCurrent,
        ),
        (
            TrustedDeviceItem::WorkgroupCollectivesCurrent,
            ProductionTerminalExpansionV1::WorkgroupCollectiveContextCurrent,
        ),
        (
            TrustedDeviceItem::WorkgroupReduceSum,
            ProductionTerminalExpansionV1::NeutralWorkgroupReduceSum,
        ),
        (
            TrustedDeviceItem::WorkgroupInclusiveScanSum,
            ProductionTerminalExpansionV1::NeutralWorkgroupInclusiveScanSum,
        ),
        (
            TrustedDeviceItem::WorkgroupExclusiveScanSum,
            ProductionTerminalExpansionV1::NeutralWorkgroupExclusiveScanSum,
        ),
        (
            TrustedDeviceItem::Gfx942SubgroupReduceSumF32,
            ProductionTerminalExpansionV1::SubgroupReduceSumF32,
        ),
        (
            TrustedDeviceItem::Gfx942SubgroupReduceMaxF32,
            ProductionTerminalExpansionV1::SubgroupReduceMaxF32,
        ),
        (
            TrustedDeviceItem::WaveLaneCurrent,
            ProductionTerminalExpansionV1::WaveLaneCurrent,
        ),
        (
            TrustedDeviceItem::DeviceMatrixCurrent,
            ProductionTerminalExpansionV1::MatrixContextCurrent,
        ),
        (
            TrustedDeviceItem::Bf16MfmaMatrixARowMajor,
            ProductionTerminalExpansionV1::Bf16MatrixARowMajor,
        ),
        (
            TrustedDeviceItem::Bf16MfmaMatrixBRowMajor,
            ProductionTerminalExpansionV1::Bf16MatrixBRowMajor,
        ),
        (
            TrustedDeviceItem::Bf16MfmaBColumnMajor,
            ProductionTerminalExpansionV1::Bf16MatrixBColumnMajor,
        ),
        (
            TrustedDeviceItem::Bf16MfmaBColumnMajorLoadZeroFilledV1,
            ProductionTerminalExpansionV1::Bf16MatrixBColumnMajorLoadZeroFilledV1,
        ),
        (
            TrustedDeviceItem::Bf16MfmaMatrixALoadZeroFilledV2,
            ProductionTerminalExpansionV1::Bf16MatrixALoadZeroFilledV2,
        ),
        (
            TrustedDeviceItem::Bf16MfmaMatrixBLoadZeroFilledV2,
            ProductionTerminalExpansionV1::Bf16MatrixBLoadZeroFilledV2,
        ),
        (
            TrustedDeviceItem::F32AccumulatorFragmentZero,
            ProductionTerminalExpansionV1::F32MatrixAccumulatorZero,
        ),
        (
            TrustedDeviceItem::F32AccumulatorFragmentIntoValues,
            ProductionTerminalExpansionV1::F32MatrixAccumulatorIntoValues,
        ),
        (
            TrustedDeviceItem::DeviceMatrixMultiplyAccumulate,
            ProductionTerminalExpansionV1::MatrixMultiplyAccumulate,
        ),
        (
            TrustedDeviceItem::Gfx950MatrixCurrent,
            ProductionTerminalExpansionV1::Gfx950MatrixContextCurrent,
        ),
        (
            TrustedDeviceItem::Gfx950MfmaMatrixAFp4RowMajor,
            ProductionTerminalExpansionV1::Gfx950Fp4MatrixARowMajor,
        ),
        (
            TrustedDeviceItem::Gfx950MfmaMatrixBFp4RowMajor,
            ProductionTerminalExpansionV1::Gfx950Fp4MatrixBRowMajor,
        ),
        (
            TrustedDeviceItem::Gfx950MfmaMatrixAFp4LoadM16K128,
            ProductionTerminalExpansionV1::Gfx950Fp4MatrixALoadM16K128,
        ),
        (
            TrustedDeviceItem::Gfx950MfmaMatrixBFp4LoadK128N16,
            ProductionTerminalExpansionV1::Gfx950Fp4MatrixBLoadK128N16,
        ),
        (
            TrustedDeviceItem::Gfx950Fp4F32AccumulatorFragmentZero,
            ProductionTerminalExpansionV1::Gfx950Fp4AccumulatorZero,
        ),
        (
            TrustedDeviceItem::Gfx950Fp4F32AccumulatorFragmentIntoValues,
            ProductionTerminalExpansionV1::Gfx950Fp4AccumulatorIntoValues,
        ),
        (
            TrustedDeviceItem::Gfx950MatrixMultiplyAccumulateFp4,
            ProductionTerminalExpansionV1::Gfx950Fp4MultiplyAccumulate,
        ),
        (
            TrustedDeviceItem::Gfx950MatrixMultiplyAccumulateFp4Fp8,
            ProductionTerminalExpansionV1::Gfx950Fp4Fp8MultiplyAccumulate,
        ),
        (
            TrustedDeviceItem::Gfx950MfmaMatrixARowMajor,
            ProductionTerminalExpansionV1::Gfx950Fp8MatrixARowMajor,
        ),
        (
            TrustedDeviceItem::Gfx950MfmaMatrixBRowMajor,
            ProductionTerminalExpansionV1::Gfx950Fp8MatrixBRowMajor,
        ),
        (
            TrustedDeviceItem::Gfx950MfmaMatrixAFp8LoadM16K128,
            ProductionTerminalExpansionV1::Gfx950Fp8MatrixALoadM16K128,
        ),
        (
            TrustedDeviceItem::Gfx950MfmaMatrixBFp8LoadK128N16,
            ProductionTerminalExpansionV1::Gfx950Fp8MatrixBLoadK128N16,
        ),
        (
            TrustedDeviceItem::Gfx950F32AccumulatorFragmentZero,
            ProductionTerminalExpansionV1::Gfx950Fp8AccumulatorZero,
        ),
        (
            TrustedDeviceItem::Gfx950F32AccumulatorFragmentIntoValues,
            ProductionTerminalExpansionV1::Gfx950Fp8AccumulatorIntoValues,
        ),
        (
            TrustedDeviceItem::Gfx950MatrixMultiplyAccumulateFp8,
            ProductionTerminalExpansionV1::Gfx950Fp8MultiplyAccumulate,
        ),
        (
            TrustedDeviceItem::AmdGpuDiagnostic(TrustedAmdGpuDiagnosticOperation::Trap),
            ProductionTerminalExpansionV1::Trap,
        ),
        (
            TrustedDeviceItem::ThreadIndexCheckedTiled2D,
            ProductionTerminalExpansionV1::ThreadIndexCheckedTiled2d,
        ),
        (
            TrustedDeviceItem::DisjointSliceGetTiled2DMut,
            ProductionTerminalExpansionV1::DisjointSliceGetTiled2dMut,
        ),
        (
            TrustedDeviceItem::ThreadIndexCheckedRowStriped2D,
            ProductionTerminalExpansionV1::ThreadIndexCheckedRowStriped2d,
        ),
        (
            TrustedDeviceItem::DisjointSliceGetRowStriped2DMut,
            ProductionTerminalExpansionV1::DisjointSliceGetRowStriped2dMut,
        ),
        (
            TrustedDeviceItem::MemoryVolatileLoad,
            ProductionTerminalExpansionV1::MemoryVolatileLoad,
        ),
        (
            TrustedDeviceItem::WorkgroupLdsScopeCurrent,
            ProductionTerminalExpansionV1::WorkgroupLdsScopeCurrent,
        ),
    ];
    for (item, expansion) in cases {
        let rule = ProductionSemanticTerminalRuleV1::from_trusted_device_item(item);
        assert_eq!(rule, ProductionSemanticTerminalRuleV1::Expand(expansion));
        assert_eq!(rule.trusted_device_item(), item);
    }
}

#[test]
fn every_unimplemented_terminal_is_retained_as_an_explicit_rejection() {
    for item in [
        TrustedDeviceItem::KernelContext,
        TrustedDeviceItem::ExecutionWorkgroupCapability,
        TrustedDeviceItem::MaskedTile1D,
        TrustedDeviceItem::LaneFragment1D,
        TrustedDeviceItem::MemoryVolatileStore,
        TrustedDeviceItem::MemoryCopyNonOverlapping,
        TrustedDeviceItem::MemoryCopyOneNonOverlapping,
        TrustedDeviceItem::HalfOperation(TrustedHalfOperation::FromBits(NarrowFloatFormat::F16)),
        TrustedDeviceItem::HalfOperation(TrustedHalfOperation::ToBits(NarrowFloatFormat::F16)),
        TrustedDeviceItem::HalfOperation(TrustedHalfOperation::FromF32(NarrowFloatFormat::F16)),
        TrustedDeviceItem::HalfOperation(TrustedHalfOperation::ToF32(NarrowFloatFormat::F16)),
    ] {
        let rule = ProductionSemanticTerminalRuleV1::from_trusted_device_item(item);
        assert_eq!(rule, ProductionSemanticTerminalRuleV1::Reject(item));
        assert_eq!(rule.trusted_device_item(), item);
        assert!(!is_traversed_reviewed_helper_v1(item));
    }
}

#[test]
fn reviewed_rust_helpers_are_traversed_instead_of_hidden_by_a_terminal() {
    for item in [
        TrustedDeviceItem::ExecutionWithWorkgroup,
        TrustedDeviceItem::Invocation3DCurrent,
        TrustedDeviceItem::DeviceGlobalMutPtrU32AsAtomic,
        TrustedDeviceItem::DeviceGlobalMutPtrI32AsAtomic,
        TrustedDeviceItem::DeviceGlobalMutPtrU64AsAtomic,
        TrustedDeviceItem::DeviceGlobalMutPtrI64AsAtomic,
    ] {
        assert!(is_traversed_reviewed_helper_v1(item));
    }
}
